/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;
import types.AudioOutputType;
import types.VideoOutputTypeWithoutAvi;

@JsonDeserialize(
    using = DubbedOutputInAltFormatRequestPayloadOutputFormat.Deserializer.class
)
public final class DubbedOutputInAltFormatRequestPayloadOutputFormat {
  private final Object value;

  private final int type;

  private DubbedOutputInAltFormatRequestPayloadOutputFormat(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((AudioOutputType) this.value);
    } else if(this.type == 1) {
      return visitor.visit((VideoOutputTypeWithoutAvi) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DubbedOutputInAltFormatRequestPayloadOutputFormat && equalTo((DubbedOutputInAltFormatRequestPayloadOutputFormat) other);
  }

  private boolean equalTo(DubbedOutputInAltFormatRequestPayloadOutputFormat other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static DubbedOutputInAltFormatRequestPayloadOutputFormat of(AudioOutputType value) {
    return new DubbedOutputInAltFormatRequestPayloadOutputFormat(value, 0);
  }

  public static DubbedOutputInAltFormatRequestPayloadOutputFormat of(
      VideoOutputTypeWithoutAvi value) {
    return new DubbedOutputInAltFormatRequestPayloadOutputFormat(value, 1);
  }

  public interface Visitor<T> {
    T visit(AudioOutputType value);

    T visit(VideoOutputTypeWithoutAvi value);
  }

  static final class Deserializer extends StdDeserializer<DubbedOutputInAltFormatRequestPayloadOutputFormat> {
    Deserializer() {
      super(DubbedOutputInAltFormatRequestPayloadOutputFormat.class);
    }

    @java.lang.Override
    public DubbedOutputInAltFormatRequestPayloadOutputFormat deserialize(JsonParser p,
        DeserializationContext ctxt) throws IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, AudioOutputType.class));
      } catch(IllegalArgumentException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, VideoOutputTypeWithoutAvi.class));
      } catch(IllegalArgumentException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
