/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import types.OrchestratorPipelineCallResult;

@JsonDeserialize(
    using = GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse.Deserializer.class
)
public final class GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse {
  private final Object value;

  private final int type;

  private GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((Map<String, String>) this.value);
    } else if(this.type == 1) {
      return visitor.visit((OrchestratorPipelineCallResult) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse && equalTo((GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse) other);
  }

  private boolean equalTo(GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse of(
      Map<String, String> value) {
    return new GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse(value, 0);
  }

  public static GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse of(
      OrchestratorPipelineCallResult value) {
    return new GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse(value, 1);
  }

  public interface Visitor<T> {
    T visit(Map<String, String> value);

    T visit(OrchestratorPipelineCallResult value);
  }

  static final class Deserializer extends StdDeserializer<GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse> {
    Deserializer() {
      super(GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse.class);
    }

    @java.lang.Override
    public GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse deserialize(JsonParser p,
        DeserializationContext ctxt) throws IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<Map<String, String>>() {}));
      } catch(IllegalArgumentException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, OrchestratorPipelineCallResult.class));
      } catch(IllegalArgumentException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
