/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translatedtts;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.translatedtts.requests.CreateTranslatedTtsRequestPayload;
import resources.translatedtts.requests.GetTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest;
import types.CreateTranslatedTtsOut;
import types.HttpValidationError;
import types.OrchestratorPipelineResult;

public class TranslatedTtsClient {
  protected final ClientOptions clientOptions;

  public TranslatedTtsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CreateTranslatedTtsOut createTranslatedTts(CreateTranslatedTtsRequestPayload request) {
    return createTranslatedTts(request,null);
  }

  public CreateTranslatedTtsOut createTranslatedTts(CreateTranslatedTtsRequestPayload request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("translated-tts");if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("text", request.getText());
      properties.put("voice_id", request.getVoiceId());
      if (request.getAge().isPresent()) {
        properties.put("age", request.getAge());
      }
      if (request.getFormality().isPresent()) {
        properties.put("formality", request.getFormality());
      }
      if (request.getGender().isPresent()) {
        properties.put("gender", request.getGender());
      }
      properties.put("source_language", request.getSourceLanguage());
      properties.put("target_language", request.getTargetLanguage());
      if (request.getChosenDictionaries().isPresent()) {
        properties.put("chosen_dictionaries", request.getChosenDictionaries());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      if (request.getTraceparent().isPresent()) {
        _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateTranslatedTtsOut.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public OrchestratorPipelineResult getTranslatedTtsTaskStatus(String taskId) {
      return getTranslatedTtsTaskStatus(taskId,GetTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest.builder().build());
    }

    public OrchestratorPipelineResult getTranslatedTtsTaskStatus(String taskId,
        GetTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest request) {
      return getTranslatedTtsTaskStatus(taskId,request,null);
    }

    public OrchestratorPipelineResult getTranslatedTtsTaskStatus(String taskId,
        GetTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("translated-tts")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }
    }
