/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttospeech;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import core.ResponseBodyInputStream;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.texttospeech.requests.CreateStreamTtsRequestPayload;
import resources.texttospeech.requests.CreateTtsRequestPayload;
import resources.texttospeech.requests.GetTtsResultDiscordDiscordTtsTaskIdGetRequest;
import resources.texttospeech.requests.GetTtsResultTtsTaskIdGetRequest;
import resources.texttospeech.requests.GetTtsResultsTtsResultsPostRequest;
import resources.texttospeech.requests.GetTtsRunInfoTtsResultRunIdGetRequest;
import resources.texttospeech.types.GetTtsResultsTtsResultsPostResponseValue;
import resources.texttospeech.types.GetTtsRunInfoTtsResultRunIdGetResponse;
import types.CreateTtsOut;
import types.HttpValidationError;
import types.OrchestratorPipelineResult;

public class TextToSpeechClient {
  protected final ClientOptions clientOptions;

  public TextToSpeechClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public InputStream tts(CreateStreamTtsRequestPayload request) {
    return tts(request,null);
  }

  public InputStream tts(CreateStreamTtsRequestPayload request, RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("tts-stream")
      .build();
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
    }
    catch(JsonProcessingException e) {
      throw new CambApiException("Failed to serialize request", e);
    }
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try {
      Response response = client.newCall(okhttpRequest).execute();
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return new ResponseBodyInputStream(response);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 422) {
          throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
    }
    catch (IOException e) {
      throw new CambApiException("Network error executing HTTP request", e);
    }
  }

  public CreateTtsOut createTts(CreateTtsRequestPayload request) {
    return createTts(request,null);
  }

  public CreateTtsOut createTts(CreateTtsRequestPayload request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("tts");if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("text", request.getText());
      properties.put("voice_id", request.getVoiceId());
      properties.put("language", request.getLanguage());
      if (request.getGender().isPresent()) {
        properties.put("gender", request.getGender());
      }
      if (request.getAge().isPresent()) {
        properties.put("age", request.getAge());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateTtsOut.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public OrchestratorPipelineResult getTtsResult(String taskId) {
      return getTtsResult(taskId,GetTtsResultTtsTaskIdGetRequest.builder().build());
    }

    public OrchestratorPipelineResult getTtsResult(String taskId,
        GetTtsResultTtsTaskIdGetRequest request) {
      return getTtsResult(taskId,request,null);
    }

    public OrchestratorPipelineResult getTtsResult(String taskId,
        GetTtsResultTtsTaskIdGetRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("tts")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Retrieves the result of a Text To Speech (TTS) run.
       * <p>This endpoint validates the provided <code>run_id</code> and fetches the corresponding TTS-generated audio.
       * The user must have valid access to the run. The function supports two output formats:</p>
       * <ul>
       * <li><code>RAW_BYTES</code>: Streams the audio file directly.</li>
       * <li><code>FILE_URL</code>: Returns a pre-signed URL to download the audio file.</li>
       * </ul>
       * <p>Args:
       * run_id (int): Unique identifier for the TTS run.
       * api_key_obj (dict): API key object used for authentication and storage preferences.
       * traceparent (Optional[str]): Traceparent header for distributed tracing.
       * output_type (OutputType, optional): Determines the output format. Defaults to <code>RAW_BYTES</code>.</p>
       * <p>Returns:
       * StreamingResponse | GetTTSOut:
       * - If <code>output_type = RAW_BYTES</code>: A streaming response containing the TTS-generated audio in FLAC format.
       * - If <code>output_type = FILE_URL</code>: A URL pointing to the stored TTS-generated audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST if the run ID is invalid or does not belong to a TTS process.
       * - 500 INTERNAL SERVER ERROR if fetching or streaming the audio fails.</p>
       * <p>Assumptions:
       * - The user has valid access to the <code>run_id</code>.
       * - The <code>run_id</code> corresponds to a valid TTS run.
       * - There is only <strong>one</strong> dialogue associated with the given <code>run_id</code>.</p>
       */
      public GetTtsRunInfoTtsResultRunIdGetResponse getTtsRunInfo(Optional<Integer> runId) {
        return getTtsRunInfo(runId,GetTtsRunInfoTtsResultRunIdGetRequest.builder().build());
      }

      /**
       * Retrieves the result of a Text To Speech (TTS) run.
       * <p>This endpoint validates the provided <code>run_id</code> and fetches the corresponding TTS-generated audio.
       * The user must have valid access to the run. The function supports two output formats:</p>
       * <ul>
       * <li><code>RAW_BYTES</code>: Streams the audio file directly.</li>
       * <li><code>FILE_URL</code>: Returns a pre-signed URL to download the audio file.</li>
       * </ul>
       * <p>Args:
       * run_id (int): Unique identifier for the TTS run.
       * api_key_obj (dict): API key object used for authentication and storage preferences.
       * traceparent (Optional[str]): Traceparent header for distributed tracing.
       * output_type (OutputType, optional): Determines the output format. Defaults to <code>RAW_BYTES</code>.</p>
       * <p>Returns:
       * StreamingResponse | GetTTSOut:
       * - If <code>output_type = RAW_BYTES</code>: A streaming response containing the TTS-generated audio in FLAC format.
       * - If <code>output_type = FILE_URL</code>: A URL pointing to the stored TTS-generated audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST if the run ID is invalid or does not belong to a TTS process.
       * - 500 INTERNAL SERVER ERROR if fetching or streaming the audio fails.</p>
       * <p>Assumptions:
       * - The user has valid access to the <code>run_id</code>.
       * - The <code>run_id</code> corresponds to a valid TTS run.
       * - There is only <strong>one</strong> dialogue associated with the given <code>run_id</code>.</p>
       */
      public GetTtsRunInfoTtsResultRunIdGetResponse getTtsRunInfo(Optional<Integer> runId,
          GetTtsRunInfoTtsResultRunIdGetRequest request) {
        return getTtsRunInfo(runId,request,null);
      }

      /**
       * Retrieves the result of a Text To Speech (TTS) run.
       * <p>This endpoint validates the provided <code>run_id</code> and fetches the corresponding TTS-generated audio.
       * The user must have valid access to the run. The function supports two output formats:</p>
       * <ul>
       * <li><code>RAW_BYTES</code>: Streams the audio file directly.</li>
       * <li><code>FILE_URL</code>: Returns a pre-signed URL to download the audio file.</li>
       * </ul>
       * <p>Args:
       * run_id (int): Unique identifier for the TTS run.
       * api_key_obj (dict): API key object used for authentication and storage preferences.
       * traceparent (Optional[str]): Traceparent header for distributed tracing.
       * output_type (OutputType, optional): Determines the output format. Defaults to <code>RAW_BYTES</code>.</p>
       * <p>Returns:
       * StreamingResponse | GetTTSOut:
       * - If <code>output_type = RAW_BYTES</code>: A streaming response containing the TTS-generated audio in FLAC format.
       * - If <code>output_type = FILE_URL</code>: A URL pointing to the stored TTS-generated audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST if the run ID is invalid or does not belong to a TTS process.
       * - 500 INTERNAL SERVER ERROR if fetching or streaming the audio fails.</p>
       * <p>Assumptions:
       * - The user has valid access to the <code>run_id</code>.
       * - The <code>run_id</code> corresponds to a valid TTS run.
       * - There is only <strong>one</strong> dialogue associated with the given <code>run_id</code>.</p>
       */
      public GetTtsRunInfoTtsResultRunIdGetResponse getTtsRunInfo(Optional<Integer> runId,
          GetTtsRunInfoTtsResultRunIdGetRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("tts-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }
          if (request.getOutputType().isPresent()) {
            httpUrl.addQueryParameter("output_type", request.getOutputType().get());
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTtsRunInfoTtsResultRunIdGetResponse.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
          catch (IOException e) {
            throw new CambApiException("Network error executing HTTP request", e);
          }
        }

        public Map<String, GetTtsResultsTtsResultsPostResponseValue> getTtsResults(
            GetTtsResultsTtsResultsPostRequest request) {
          return getTtsResults(request,null);
        }

        public Map<String, GetTtsResultsTtsResultsPostResponseValue> getTtsResults(
            GetTtsResultsTtsResultsPostRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("tts-results");if (request.getRunId().isPresent()) {
              httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json");
            if (request.getTraceparent().isPresent()) {
              _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
            }
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, GetTtsResultsTtsResultsPostResponseValue>>() {});
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            }
            catch (IOException e) {
              throw new CambApiException("Network error executing HTTP request", e);
            }
          }

          public OrchestratorPipelineResult getTtsResultDiscord(String taskId) {
            return getTtsResultDiscord(taskId,GetTtsResultDiscordDiscordTtsTaskIdGetRequest.builder().build());
          }

          public OrchestratorPipelineResult getTtsResultDiscord(String taskId,
              GetTtsResultDiscordDiscordTtsTaskIdGetRequest request) {
            return getTtsResultDiscord(taskId,request,null);
          }

          public OrchestratorPipelineResult getTtsResultDiscord(String taskId,
              GetTtsResultDiscordDiscordTtsTaskIdGetRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("discord/tts")
              .addPathSegment(taskId);if (request.getRunId().isPresent()) {
                httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                if (response.isSuccessful()) {
                  return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class);
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
              }
              catch (IOException e) {
                throw new CambApiException("Network error executing HTTP request", e);
              }
            }
          }
