/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.folders.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateFolderPayload.Builder.class
)
public final class CreateFolderPayload {
  private final Optional<Integer> runId;

  private final String folderName;

  private final Map<String, Object> additionalProperties;

  private CreateFolderPayload(Optional<Integer> runId, String folderName,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.folderName = folderName;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("folder_name")
  public String getFolderName() {
    return folderName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateFolderPayload && equalTo((CreateFolderPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateFolderPayload other) {
    return runId.equals(other.runId) && folderName.equals(other.folderName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.folderName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FolderNameStage builder() {
    return new Builder();
  }

  public interface FolderNameStage {
    _FinalStage folderName(@NotNull String folderName);

    Builder from(CreateFolderPayload other);
  }

  public interface _FinalStage {
    CreateFolderPayload build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FolderNameStage, _FinalStage {
    private String folderName;

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateFolderPayload other) {
      runId(other.getRunId());
      folderName(other.getFolderName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("folder_name")
    public _FinalStage folderName(@NotNull String folderName) {
      this.folderName = Objects.requireNonNull(folderName, "folderName must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public CreateFolderPayload build() {
      return new CreateFolderPayload(runId, folderName, additionalProperties);
    }
  }
}
