/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translatedstory.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTranslationForExistingStoryRequestPayload.Builder.class
)
public final class CreateTranslationForExistingStoryRequestPayload {
  private final int targetLanguage;

  private final Map<String, Object> additionalProperties;

  private CreateTranslationForExistingStoryRequestPayload(int targetLanguage,
      Map<String, Object> additionalProperties) {
    this.targetLanguage = targetLanguage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("target_language")
  public int getTargetLanguage() {
    return targetLanguage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTranslationForExistingStoryRequestPayload && equalTo((CreateTranslationForExistingStoryRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTranslationForExistingStoryRequestPayload other) {
    return targetLanguage == other.targetLanguage;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.targetLanguage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TargetLanguageStage builder() {
    return new Builder();
  }

  public interface TargetLanguageStage {
    _FinalStage targetLanguage(int targetLanguage);

    Builder from(CreateTranslationForExistingStoryRequestPayload other);
  }

  public interface _FinalStage {
    CreateTranslationForExistingStoryRequestPayload build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TargetLanguageStage, _FinalStage {
    private int targetLanguage;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTranslationForExistingStoryRequestPayload other) {
      targetLanguage(other.getTargetLanguage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("target_language")
    public _FinalStage targetLanguage(int targetLanguage) {
      this.targetLanguage = targetLanguage;
      return this;
    }

    @java.lang.Override
    public CreateTranslationForExistingStoryRequestPayload build() {
      return new CreateTranslationForExistingStoryRequestPayload(targetLanguage, additionalProperties);
    }
  }
}
