/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translatedtts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTranslatedTtsRequestPayload.Builder.class
)
public final class CreateTranslatedTtsRequestPayload {
  private final Optional<String> traceparent;

  private final Optional<Integer> runId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final String text;

  private final int voiceId;

  private final Optional<Integer> age;

  private final Optional<Integer> formality;

  private final Optional<Integer> gender;

  private final int sourceLanguage;

  private final int targetLanguage;

  private final Optional<List<Integer>> chosenDictionaries;

  private final Map<String, Object> additionalProperties;

  private CreateTranslatedTtsRequestPayload(Optional<String> traceparent, Optional<Integer> runId,
      Optional<String> projectName, Optional<String> projectDescription, Optional<Integer> folderId,
      String text, int voiceId, Optional<Integer> age, Optional<Integer> formality,
      Optional<Integer> gender, int sourceLanguage, int targetLanguage,
      Optional<List<Integer>> chosenDictionaries, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.runId = runId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.text = text;
    this.voiceId = voiceId;
    this.age = age;
    this.formality = formality;
    this.gender = gender;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguage = targetLanguage;
    this.chosenDictionaries = chosenDictionaries;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("traceparent")
  public Optional<String> getTraceparent() {
    return traceparent;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @JsonProperty("voice_id")
  public int getVoiceId() {
    return voiceId;
  }

  @JsonProperty("age")
  public Optional<Integer> getAge() {
    return age;
  }

  @JsonProperty("formality")
  public Optional<Integer> getFormality() {
    return formality;
  }

  @JsonProperty("gender")
  public Optional<Integer> getGender() {
    return gender;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_language")
  public int getTargetLanguage() {
    return targetLanguage;
  }

  @JsonProperty("chosen_dictionaries")
  public Optional<List<Integer>> getChosenDictionaries() {
    return chosenDictionaries;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTranslatedTtsRequestPayload && equalTo((CreateTranslatedTtsRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTranslatedTtsRequestPayload other) {
    return traceparent.equals(other.traceparent) && runId.equals(other.runId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId) && text.equals(other.text) && voiceId == other.voiceId && age.equals(other.age) && formality.equals(other.formality) && gender.equals(other.gender) && sourceLanguage == other.sourceLanguage && targetLanguage == other.targetLanguage && chosenDictionaries.equals(other.chosenDictionaries);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.runId, this.projectName, this.projectDescription, this.folderId, this.text, this.voiceId, this.age, this.formality, this.gender, this.sourceLanguage, this.targetLanguage, this.chosenDictionaries);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TextStage builder() {
    return new Builder();
  }

  public interface TextStage {
    VoiceIdStage text(@NotNull String text);

    Builder from(CreateTranslatedTtsRequestPayload other);
  }

  public interface VoiceIdStage {
    SourceLanguageStage voiceId(int voiceId);
  }

  public interface SourceLanguageStage {
    TargetLanguageStage sourceLanguage(int sourceLanguage);
  }

  public interface TargetLanguageStage {
    _FinalStage targetLanguage(int targetLanguage);
  }

  public interface _FinalStage {
    CreateTranslatedTtsRequestPayload build();

    _FinalStage traceparent(Optional<String> traceparent);

    _FinalStage traceparent(String traceparent);

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage age(Optional<Integer> age);

    _FinalStage age(Integer age);

    _FinalStage formality(Optional<Integer> formality);

    _FinalStage formality(Integer formality);

    _FinalStage gender(Optional<Integer> gender);

    _FinalStage gender(Integer gender);

    _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries);

    _FinalStage chosenDictionaries(List<Integer> chosenDictionaries);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TextStage, VoiceIdStage, SourceLanguageStage, TargetLanguageStage, _FinalStage {
    private String text;

    private int voiceId;

    private int sourceLanguage;

    private int targetLanguage;

    private Optional<List<Integer>> chosenDictionaries = Optional.empty();

    private Optional<Integer> gender = Optional.empty();

    private Optional<Integer> formality = Optional.empty();

    private Optional<Integer> age = Optional.empty();

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    private Optional<String> traceparent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTranslatedTtsRequestPayload other) {
      traceparent(other.getTraceparent());
      runId(other.getRunId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      text(other.getText());
      voiceId(other.getVoiceId());
      age(other.getAge());
      formality(other.getFormality());
      gender(other.getGender());
      sourceLanguage(other.getSourceLanguage());
      targetLanguage(other.getTargetLanguage());
      chosenDictionaries(other.getChosenDictionaries());
      return this;
    }

    @java.lang.Override
    @JsonSetter("text")
    public VoiceIdStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("voice_id")
    public SourceLanguageStage voiceId(int voiceId) {
      this.voiceId = voiceId;
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public TargetLanguageStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("target_language")
    public _FinalStage targetLanguage(int targetLanguage) {
      this.targetLanguage = targetLanguage;
      return this;
    }

    @java.lang.Override
    public _FinalStage chosenDictionaries(List<Integer> chosenDictionaries) {
      this.chosenDictionaries = Optional.ofNullable(chosenDictionaries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "chosen_dictionaries",
        nulls = Nulls.SKIP
    )
    public _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries) {
      this.chosenDictionaries = chosenDictionaries;
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(Integer gender) {
      this.gender = Optional.ofNullable(gender);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gender",
        nulls = Nulls.SKIP
    )
    public _FinalStage gender(Optional<Integer> gender) {
      this.gender = gender;
      return this;
    }

    @java.lang.Override
    public _FinalStage formality(Integer formality) {
      this.formality = Optional.ofNullable(formality);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "formality",
        nulls = Nulls.SKIP
    )
    public _FinalStage formality(Optional<Integer> formality) {
      this.formality = formality;
      return this;
    }

    @java.lang.Override
    public _FinalStage age(Integer age) {
      this.age = Optional.ofNullable(age);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "age",
        nulls = Nulls.SKIP
    )
    public _FinalStage age(Optional<Integer> age) {
      this.age = age;
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public _FinalStage traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    @java.lang.Override
    public CreateTranslatedTtsRequestPayload build() {
      return new CreateTranslatedTtsRequestPayload(traceparent, runId, projectName, projectDescription, folderId, text, voiceId, age, formality, gender, sourceLanguage, targetLanguage, chosenDictionaries, additionalProperties);
    }
  }
}
