/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.voicecloning.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import types.Voice;

@JsonDeserialize(
    using = ListVoicesListVoicesGetResponseItem.Deserializer.class
)
public final class ListVoicesListVoicesGetResponseItem {
  private final Object value;

  private final int type;

  private ListVoicesListVoicesGetResponseItem(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((Map<String, Object>) this.value);
    } else if(this.type == 1) {
      return visitor.visit((Voice) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListVoicesListVoicesGetResponseItem && equalTo((ListVoicesListVoicesGetResponseItem) other);
  }

  private boolean equalTo(ListVoicesListVoicesGetResponseItem other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static ListVoicesListVoicesGetResponseItem of(Map<String, Object> value) {
    return new ListVoicesListVoicesGetResponseItem(value, 0);
  }

  public static ListVoicesListVoicesGetResponseItem of(Voice value) {
    return new ListVoicesListVoicesGetResponseItem(value, 1);
  }

  public interface Visitor<T> {
    T visit(Map<String, Object> value);

    T visit(Voice value);
  }

  static final class Deserializer extends StdDeserializer<ListVoicesListVoicesGetResponseItem> {
    Deserializer() {
      super(ListVoicesListVoicesGetResponseItem.class);
    }

    @java.lang.Override
    public ListVoicesListVoicesGetResponseItem deserialize(JsonParser p,
        DeserializationContext ctxt) throws IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<Map<String, Object>>() {}));
      } catch(IllegalArgumentException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, Voice.class));
      } catch(IllegalArgumentException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
