/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.folders;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.folders.requests.CreateFolderPayload;
import resources.folders.requests.ListFoldersFoldersGetRequest;
import types.Folder;
import types.HttpValidationError;

public class FoldersClient {
  protected final ClientOptions clientOptions;

  public FoldersClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public List<Folder> listFolders() {
    return listFolders(ListFoldersFoldersGetRequest.builder().build());
  }

  public List<Folder> listFolders(ListFoldersFoldersGetRequest request) {
    return listFolders(request,null);
  }

  public List<Folder> listFolders(ListFoldersFoldersGetRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("folders");if (request.getLimit().isPresent()) {
        httpUrl.addQueryParameter("limit", request.getLimit().get().toString());
      }
      if (request.getSearchQuery().isPresent()) {
        httpUrl.addQueryParameter("search_query", request.getSearchQuery().get());
      }
      if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<Folder>>() {});
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public Object createFolder(CreateFolderPayload request) {
      return createFolder(request,null);
    }

    public Object createFolder(CreateFolderPayload request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("folders/create");if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("folder_name", request.getFolderName());
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }
    }
