/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.deprecatedstreaming;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.deprecatedstreaming.requests.GetProbeStreamV1StreamProbePostRequest;
import resources.deprecatedstreaming.requests.GetStreamResultV1StreamStreamIdGetRequest;
import resources.deprecatedstreaming.requests.StopStreamV1StreamStreamIdStopGetRequest;
import types.CreateStreamOut;
import types.CreateStreamRequestPayload;
import types.GetProbeStreamOut;
import types.HttpValidationError;

public class DeprecatedStreamingClient {
  protected final ClientOptions clientOptions;

  public DeprecatedStreamingClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CreateStreamOut createStream(CreateStreamRequestPayload request) {
    return createStream(request,null);
  }

  public CreateStreamOut createStream(CreateStreamRequestPayload request,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/stream")
      .build();
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
    }
    catch(JsonProcessingException e) {
      throw new CambApiException("Failed to serialize request", e);
    }
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateStreamOut.class);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      try {
        if (response.code() == 422) {
          throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
    }
    catch (IOException e) {
      throw new CambApiException("Network error executing HTTP request", e);
    }
  }

  public Map<String, Object> getStreamResult(int streamId) {
    return getStreamResult(streamId,GetStreamResultV1StreamStreamIdGetRequest.builder().build());
  }

  public Map<String, Object> getStreamResult(int streamId,
      GetStreamResultV1StreamStreamIdGetRequest request) {
    return getStreamResult(streamId,request,null);
  }

  public Map<String, Object> getStreamResult(int streamId,
      GetStreamResultV1StreamStreamIdGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/stream")
      .addPathSegment(Integer.toString(streamId));if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, Object>>() {});
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public Map<String, Object> stopStream(int streamId) {
      return stopStream(streamId,StopStreamV1StreamStreamIdStopGetRequest.builder().build());
    }

    public Map<String, Object> stopStream(int streamId,
        StopStreamV1StreamStreamIdStopGetRequest request) {
      return stopStream(streamId,request,null);
    }

    public Map<String, Object> stopStream(int streamId,
        StopStreamV1StreamStreamIdStopGetRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("v1/stream")
        .addPathSegment(Integer.toString(streamId))
        .addPathSegments("stop");if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, Object>>() {});
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }

      public GetProbeStreamOut getProbeStream(GetProbeStreamV1StreamProbePostRequest request) {
        return getProbeStream(request,null);
      }

      public GetProbeStreamOut getProbeStream(GetProbeStreamV1StreamProbePostRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("v1/stream/probe");if (request.getRunId().isPresent()) {
            httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
          }
          catch(Exception e) {
            throw new RuntimeException(e);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          if (request.getTraceparent().isPresent()) {
            _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
          }
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetProbeStreamOut.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
          catch (IOException e) {
            throw new CambApiException("Network error executing HTTP request", e);
          }
        }
      }
