/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttospeech.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CreateStreamTtsRequestPayloadSpeechModel {
  AUTO("auto"),

  MARS8("mars-8"),

  MARS8FLASH("mars-8-flash"),

  MARS8INSTRUCT("mars-8-instruct"),

  MARS7("mars-7"),

  MARS6("mars-6");

  private final String value;

  CreateStreamTtsRequestPayloadSpeechModel(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
