/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttospeech.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CreateStreamTtsRequestPayloadLanguage {
  AR_KW("ar-kw"),

  DE_CH("de-ch"),

  KO_KR("ko-kr"),

  TH_TH("th-th"),

  ML_IN("ml-in"),

  PT_PT("pt-pt"),

  KN_IN("kn-in"),

  FI_FI("fi-fi"),

  ES_MX("es-mx"),

  FR_CA("fr-ca"),

  CS_CZ("cs-cz"),

  PT_BR("pt-br"),

  HI_IN("hi-in"),

  AR_SY("ar-sy"),

  ES_US("es-us"),

  BN_BD("bn-bd"),

  JA_JP("ja-jp"),

  MR_IN("mr-in"),

  AR_MA("ar-ma"),

  ES_ES("es-es"),

  EN_US("en-us"),

  ZH_CN("zh-cn"),

  EL_GR("el-gr"),

  PL_PL("pl-pl"),

  AR_OM("ar-om"),

  FR_CH("fr-ch"),

  EN_UK("en-uk"),

  EN_AU("en-au"),

  AR_JO("ar-jo"),

  AR_AE("ar-ae"),

  TR_TR("tr-tr"),

  AR_LY("ar-ly"),

  RU_RU("ru-ru"),

  EN_IN("en-in"),

  AR_YE("ar-ye"),

  AR_EG("ar-eg"),

  FR_BE("fr-be"),

  TA_IN("ta-in"),

  ZH_TW("zh-tw"),

  VI_VN("vi-vn"),

  BN_IN("bn-in"),

  AR_SA("ar-sa"),

  DE_AT("de-at"),

  PA_IN("pa-in"),

  IT_IT("it-it"),

  NL_NL("nl-nl"),

  AR_BH("ar-bh"),

  FR_FR("fr-fr"),

  AR_QA("ar-qa"),

  UK_UA("uk-ua"),

  AR_TN("ar-tn"),

  DE_DE("de-de"),

  AR_XA("ar-xa"),

  AR_LB("ar-lb"),

  ZH_HK("zh-hk"),

  RO_RO("ro-ro"),

  AS_IN("as-in"),

  AR_IQ("ar-iq"),

  NL_BE("nl-be"),

  TE_IN("te-in"),

  ID_ID("id-id"),

  AR_DZ("ar-dz");

  private final String value;

  CreateStreamTtsRequestPayloadLanguage(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
