/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.story.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetStoryStatusStoryTaskIdGetRequest.Builder.class
)
public final class GetStoryStatusStoryTaskIdGetRequest {
  private final Optional<Integer> runId;

  private final Map<String, Object> additionalProperties;

  private GetStoryStatusStoryTaskIdGetRequest(Optional<Integer> runId,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetStoryStatusStoryTaskIdGetRequest && equalTo((GetStoryStatusStoryTaskIdGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetStoryStatusStoryTaskIdGetRequest other) {
    return runId.equals(other.runId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetStoryStatusStoryTaskIdGetRequest other) {
      runId(other.getRunId());
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    public GetStoryStatusStoryTaskIdGetRequest build() {
      return new GetStoryStatusStoryTaskIdGetRequest(runId, additionalProperties);
    }
  }
}
