/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.projectsetup.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateProjectSetupRequestPayload.Builder.class
)
public final class CreateProjectSetupRequestPayload {
  private final Optional<Integer> runId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final String mediaUrl;

  private final int sourceLanguage;

  private final List<Integer> targetLanguages;

  private final Optional<List<Integer>> selectedAudioTracks;

  private final Optional<Boolean> addOutputAsAnAudioTrack;

  private final Optional<List<Integer>> chosenDictionaries;

  private final Map<String, Object> additionalProperties;

  private CreateProjectSetupRequestPayload(Optional<Integer> runId, Optional<String> projectName,
      Optional<String> projectDescription, Optional<Integer> folderId, String mediaUrl,
      int sourceLanguage, List<Integer> targetLanguages,
      Optional<List<Integer>> selectedAudioTracks, Optional<Boolean> addOutputAsAnAudioTrack,
      Optional<List<Integer>> chosenDictionaries, Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.mediaUrl = mediaUrl;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguages = targetLanguages;
    this.selectedAudioTracks = selectedAudioTracks;
    this.addOutputAsAnAudioTrack = addOutputAsAnAudioTrack;
    this.chosenDictionaries = chosenDictionaries;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @JsonProperty("media_url")
  public String getMediaUrl() {
    return mediaUrl;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_languages")
  public List<Integer> getTargetLanguages() {
    return targetLanguages;
  }

  @JsonProperty("selected_audio_tracks")
  public Optional<List<Integer>> getSelectedAudioTracks() {
    return selectedAudioTracks;
  }

  @JsonProperty("add_output_as_an_audio_track")
  public Optional<Boolean> getAddOutputAsAnAudioTrack() {
    return addOutputAsAnAudioTrack;
  }

  @JsonProperty("chosen_dictionaries")
  public Optional<List<Integer>> getChosenDictionaries() {
    return chosenDictionaries;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateProjectSetupRequestPayload && equalTo((CreateProjectSetupRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateProjectSetupRequestPayload other) {
    return runId.equals(other.runId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId) && mediaUrl.equals(other.mediaUrl) && sourceLanguage == other.sourceLanguage && targetLanguages.equals(other.targetLanguages) && selectedAudioTracks.equals(other.selectedAudioTracks) && addOutputAsAnAudioTrack.equals(other.addOutputAsAnAudioTrack) && chosenDictionaries.equals(other.chosenDictionaries);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.projectName, this.projectDescription, this.folderId, this.mediaUrl, this.sourceLanguage, this.targetLanguages, this.selectedAudioTracks, this.addOutputAsAnAudioTrack, this.chosenDictionaries);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MediaUrlStage builder() {
    return new Builder();
  }

  public interface MediaUrlStage {
    SourceLanguageStage mediaUrl(@NotNull String mediaUrl);

    Builder from(CreateProjectSetupRequestPayload other);
  }

  public interface SourceLanguageStage {
    _FinalStage sourceLanguage(int sourceLanguage);
  }

  public interface _FinalStage {
    CreateProjectSetupRequestPayload build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage targetLanguages(List<Integer> targetLanguages);

    _FinalStage addTargetLanguages(Integer targetLanguages);

    _FinalStage addAllTargetLanguages(List<Integer> targetLanguages);

    _FinalStage selectedAudioTracks(Optional<List<Integer>> selectedAudioTracks);

    _FinalStage selectedAudioTracks(List<Integer> selectedAudioTracks);

    _FinalStage addOutputAsAnAudioTrack(Optional<Boolean> addOutputAsAnAudioTrack);

    _FinalStage addOutputAsAnAudioTrack(Boolean addOutputAsAnAudioTrack);

    _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries);

    _FinalStage chosenDictionaries(List<Integer> chosenDictionaries);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MediaUrlStage, SourceLanguageStage, _FinalStage {
    private String mediaUrl;

    private int sourceLanguage;

    private Optional<List<Integer>> chosenDictionaries = Optional.empty();

    private Optional<Boolean> addOutputAsAnAudioTrack = Optional.empty();

    private Optional<List<Integer>> selectedAudioTracks = Optional.empty();

    private List<Integer> targetLanguages = new ArrayList<>();

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateProjectSetupRequestPayload other) {
      runId(other.getRunId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      mediaUrl(other.getMediaUrl());
      sourceLanguage(other.getSourceLanguage());
      targetLanguages(other.getTargetLanguages());
      selectedAudioTracks(other.getSelectedAudioTracks());
      addOutputAsAnAudioTrack(other.getAddOutputAsAnAudioTrack());
      chosenDictionaries(other.getChosenDictionaries());
      return this;
    }

    @java.lang.Override
    @JsonSetter("media_url")
    public SourceLanguageStage mediaUrl(@NotNull String mediaUrl) {
      this.mediaUrl = Objects.requireNonNull(mediaUrl, "mediaUrl must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public _FinalStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    public _FinalStage chosenDictionaries(List<Integer> chosenDictionaries) {
      this.chosenDictionaries = Optional.ofNullable(chosenDictionaries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "chosen_dictionaries",
        nulls = Nulls.SKIP
    )
    public _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries) {
      this.chosenDictionaries = chosenDictionaries;
      return this;
    }

    @java.lang.Override
    public _FinalStage addOutputAsAnAudioTrack(Boolean addOutputAsAnAudioTrack) {
      this.addOutputAsAnAudioTrack = Optional.ofNullable(addOutputAsAnAudioTrack);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "add_output_as_an_audio_track",
        nulls = Nulls.SKIP
    )
    public _FinalStage addOutputAsAnAudioTrack(Optional<Boolean> addOutputAsAnAudioTrack) {
      this.addOutputAsAnAudioTrack = addOutputAsAnAudioTrack;
      return this;
    }

    @java.lang.Override
    public _FinalStage selectedAudioTracks(List<Integer> selectedAudioTracks) {
      this.selectedAudioTracks = Optional.ofNullable(selectedAudioTracks);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "selected_audio_tracks",
        nulls = Nulls.SKIP
    )
    public _FinalStage selectedAudioTracks(Optional<List<Integer>> selectedAudioTracks) {
      this.selectedAudioTracks = selectedAudioTracks;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllTargetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages.addAll(targetLanguages);
      return this;
    }

    @java.lang.Override
    public _FinalStage addTargetLanguages(Integer targetLanguages) {
      this.targetLanguages.add(targetLanguages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages.clear();
      this.targetLanguages.addAll(targetLanguages);
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public CreateProjectSetupRequestPayload build() {
      return new CreateProjectSetupRequestPayload(runId, projectName, projectDescription, folderId, mediaUrl, sourceLanguage, targetLanguages, selectedAudioTracks, addOutputAsAnAudioTrack, chosenDictionaries, additionalProperties);
    }
  }
}
