/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.projectsetup.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.RunIDsRequestPayload;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetProjectSetupRunsResultsProjectSetupResultsPostRequest.Builder.class
)
public final class GetProjectSetupRunsResultsProjectSetupResultsPostRequest {
  private final Optional<Integer> runId;

  private final RunIDsRequestPayload body;

  private final Map<String, Object> additionalProperties;

  private GetProjectSetupRunsResultsProjectSetupResultsPostRequest(Optional<Integer> runId,
      RunIDsRequestPayload body, Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("body")
  public RunIDsRequestPayload getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetProjectSetupRunsResultsProjectSetupResultsPostRequest && equalTo((GetProjectSetupRunsResultsProjectSetupResultsPostRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetProjectSetupRunsResultsProjectSetupResultsPostRequest other) {
    return runId.equals(other.runId) && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull RunIDsRequestPayload body);

    Builder from(GetProjectSetupRunsResultsProjectSetupResultsPostRequest other);
  }

  public interface _FinalStage {
    GetProjectSetupRunsResultsProjectSetupResultsPostRequest build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BodyStage, _FinalStage {
    private RunIDsRequestPayload body;

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetProjectSetupRunsResultsProjectSetupResultsPostRequest other) {
      runId(other.getRunId());
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull RunIDsRequestPayload body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public GetProjectSetupRunsResultsProjectSetupResultsPostRequest build() {
      return new GetProjectSetupRunsResultsProjectSetupResultsPostRequest(runId, body, additionalProperties);
    }
  }
}
