/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translatedstory;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.translatedstory.requests.CreateTranslationForExistingStoryRequestPayload;
import resources.translatedstory.requests.GetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGetRequest;
import resources.translatedstory.requests.GetTranslatedStoryStatusTranslatedStoryTaskIdGetRequest;
import types.AddTargetLanguageOut;
import types.HttpValidationError;
import types.OrchestratorPipelineResult;

public class TranslatedStoryClient {
  protected final ClientOptions clientOptions;

  public TranslatedStoryClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public AddTargetLanguageOut createTranslationForExistingStory(Optional<Integer> runId,
      CreateTranslationForExistingStoryRequestPayload request) {
    return createTranslationForExistingStory(runId,request,null);
  }

  public AddTargetLanguageOut createTranslationForExistingStory(Optional<Integer> runId,
      CreateTranslationForExistingStoryRequestPayload request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("translated-story");
      if (runId.isPresent()) {
        httpUrl.addPathSegment(runId.get().toString());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new CambApiException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), AddTargetLanguageOut.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public OrchestratorPipelineResult getTranslatedStoryStatus(String taskId) {
      return getTranslatedStoryStatus(taskId,GetTranslatedStoryStatusTranslatedStoryTaskIdGetRequest.builder().build());
    }

    public OrchestratorPipelineResult getTranslatedStoryStatus(String taskId,
        GetTranslatedStoryStatusTranslatedStoryTaskIdGetRequest request) {
      return getTranslatedStoryStatus(taskId,request,null);
    }

    public OrchestratorPipelineResult getTranslatedStoryStatus(String taskId,
        GetTranslatedStoryStatusTranslatedStoryTaskIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("translated-story")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }

      public Map<String, Object> getTranslatedStoryRunInfo(Optional<Integer> runId,
          int targetLanguage) {
        return getTranslatedStoryRunInfo(runId,targetLanguage,GetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGetRequest.builder().build());
      }

      public Map<String, Object> getTranslatedStoryRunInfo(Optional<Integer> runId,
          int targetLanguage,
          GetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGetRequest request) {
        return getTranslatedStoryRunInfo(runId,targetLanguage,request,null);
      }

      public Map<String, Object> getTranslatedStoryRunInfo(Optional<Integer> runId,
          int targetLanguage,
          GetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("translated-story-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }

          .addPathSegment(Integer.toString(targetLanguage))if (request.getIncludeTranscript().isPresent()) {
            httpUrl.addQueryParameter("include_transcript", request.getIncludeTranscript().get().toString());
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, Object>>() {});
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
          catch (IOException e) {
            throw new CambApiException("Network error executing HTTP request", e);
          }
        }
      }
