/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.transcription;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.Map;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.transcription.requests.BodyCreateTranscriptionTranscribePost;
import resources.transcription.requests.GetTranscriptionResultTranscriptionResultRunIdGetRequest;
import resources.transcription.requests.GetTranscriptionResultsTranscriptionResultsPostRequest;
import resources.transcription.requests.GetTranscriptionTaskStatusTranscribeTaskIdGetRequest;
import types.HttpValidationError;
import types.OrchestratorPipelineCallResult;
import types.OrchestratorPipelineResult;
import types.TranscriptionResult;

public class TranscriptionClient {
  protected final ClientOptions clientOptions;

  public TranscriptionClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public OrchestratorPipelineCallResult createTranscription(Optional<File> mediaFile,
      Optional<File> file, BodyCreateTranscriptionTranscribePost request) {
    return createTranscription(mediaFile,file,request,null);
  }

  public OrchestratorPipelineCallResult createTranscription(Optional<File> mediaFile,
      Optional<File> file, BodyCreateTranscriptionTranscribePost request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("transcribe");if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
      try {
        body.addFormDataPart("language", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getLanguage()));
        if (mediaFile.isPresent()) {
          String mediaFileMimeType = Files.probeContentType(mediaFile.get().toPath());
          MediaType mediaFileMimeTypeMediaType = mediaFileMimeType != null ? MediaType.parse(mediaFileMimeType) : null;
          body.addFormDataPart("media_file", mediaFile.get().getName(), RequestBody.create(mediaFileMimeTypeMediaType, mediaFile.get()));
        }
        if (request.getMediaUrl().isPresent()) {
          body.addFormDataPart("media_url", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getMediaUrl()));
        }
        if (file.isPresent()) {
          String fileMimeType = Files.probeContentType(file.get().toPath());
          MediaType fileMimeTypeMediaType = fileMimeType != null ? MediaType.parse(fileMimeType) : null;
          body.addFormDataPart("file", file.get().getName(), RequestBody.create(fileMimeTypeMediaType, file.get()));
        }
        if (request.getAudioUrl().isPresent()) {
          body.addFormDataPart("audio_url", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getAudioUrl()));
        }
        if (request.getProjectName().isPresent()) {
          body.addFormDataPart("project_name", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getProjectName()));
        }
        if (request.getProjectDescription().isPresent()) {
          body.addFormDataPart("project_description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getProjectDescription()));
        }
        if (request.getFolderId().isPresent()) {
          body.addFormDataPart("folder_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getFolderId()));
        }
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body.build())
        .headers(Headers.of(clientOptions.headers(requestOptions)));
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineCallResult.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public OrchestratorPipelineResult getTranscriptionTaskStatus(String taskId) {
      return getTranscriptionTaskStatus(taskId,GetTranscriptionTaskStatusTranscribeTaskIdGetRequest.builder().build());
    }

    public OrchestratorPipelineResult getTranscriptionTaskStatus(String taskId,
        GetTranscriptionTaskStatusTranscribeTaskIdGetRequest request) {
      return getTranscriptionTaskStatus(taskId,request,null);
    }

    public OrchestratorPipelineResult getTranscriptionTaskStatus(String taskId,
        GetTranscriptionTaskStatusTranscribeTaskIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("transcribe")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public TranscriptionResult getTranscriptionResult(Optional<Integer> runId) {
        return getTranscriptionResult(runId,GetTranscriptionResultTranscriptionResultRunIdGetRequest.builder().build());
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public TranscriptionResult getTranscriptionResult(Optional<Integer> runId,
          GetTranscriptionResultTranscriptionResultRunIdGetRequest request) {
        return getTranscriptionResult(runId,request,null);
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public TranscriptionResult getTranscriptionResult(Optional<Integer> runId,
          GetTranscriptionResultTranscriptionResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("transcription-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }
          if (request.getWordLevelTimestamps().isPresent()) {
            httpUrl.addQueryParameter("word_level_timestamps", request.getWordLevelTimestamps().get().toString());
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), TranscriptionResult.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
          catch (IOException e) {
            throw new CambApiException("Network error executing HTTP request", e);
          }
        }

        public Map<String, TranscriptionResult> getTranscriptionResults(
            GetTranscriptionResultsTranscriptionResultsPostRequest request) {
          return getTranscriptionResults(request,null);
        }

        public Map<String, TranscriptionResult> getTranscriptionResults(
            GetTranscriptionResultsTranscriptionResultsPostRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("transcription-results");if (request.getRunId().isPresent()) {
              httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json");
            if (request.getTraceparent().isPresent()) {
              _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
            }
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, TranscriptionResult>>() {});
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            }
            catch (IOException e) {
              throw new CambApiException("Network error executing HTTP request", e);
            }
          }
        }
