/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.ObjectMappers;
import core.RequestOptions;
import core.Suppliers;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.util.function.Supplier;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.audioseparation.AudioSeparationClient;
import resources.deprecatedstreaming.DeprecatedStreamingClient;
import resources.dictionaries.DictionariesClient;
import resources.dub.DubClient;
import resources.folders.FoldersClient;
import resources.languages.LanguagesClient;
import resources.projectsetup.ProjectSetupClient;
import resources.story.StoryClient;
import resources.streaming.StreamingClient;
import resources.texttoaudio.TextToAudioClient;
import resources.texttospeech.TextToSpeechClient;
import resources.texttovoice.TextToVoiceClient;
import resources.transcription.TranscriptionClient;
import resources.translatedstory.TranslatedStoryClient;
import resources.translatedtts.TranslatedTtsClient;
import resources.translation.TranslationClient;
import resources.voicecloning.VoiceCloningClient;

public class CambApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AudioSeparationClient> audioSeparationClient;

  protected final Supplier<DubClient> dubClient;

  protected final Supplier<FoldersClient> foldersClient;

  protected final Supplier<LanguagesClient> languagesClient;

  protected final Supplier<StoryClient> storyClient;

  protected final Supplier<TranslatedStoryClient> translatedStoryClient;

  protected final Supplier<TextToAudioClient> textToAudioClient;

  protected final Supplier<TextToVoiceClient> textToVoiceClient;

  protected final Supplier<TextToSpeechClient> textToSpeechClient;

  protected final Supplier<TranslationClient> translationClient;

  protected final Supplier<TranscriptionClient> transcriptionClient;

  protected final Supplier<TranslatedTtsClient> translatedTtsClient;

  protected final Supplier<StreamingClient> streamingClient;

  protected final Supplier<VoiceCloningClient> voiceCloningClient;

  protected final Supplier<DictionariesClient> dictionariesClient;

  protected final Supplier<ProjectSetupClient> projectSetupClient;

  protected final Supplier<DeprecatedStreamingClient> deprecatedStreamingClient;

  public CambApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.audioSeparationClient = Suppliers.memoize(() -> new AudioSeparationClient(clientOptions));
    this.dubClient = Suppliers.memoize(() -> new DubClient(clientOptions));
    this.foldersClient = Suppliers.memoize(() -> new FoldersClient(clientOptions));
    this.languagesClient = Suppliers.memoize(() -> new LanguagesClient(clientOptions));
    this.storyClient = Suppliers.memoize(() -> new StoryClient(clientOptions));
    this.translatedStoryClient = Suppliers.memoize(() -> new TranslatedStoryClient(clientOptions));
    this.textToAudioClient = Suppliers.memoize(() -> new TextToAudioClient(clientOptions));
    this.textToVoiceClient = Suppliers.memoize(() -> new TextToVoiceClient(clientOptions));
    this.textToSpeechClient = Suppliers.memoize(() -> new TextToSpeechClient(clientOptions));
    this.translationClient = Suppliers.memoize(() -> new TranslationClient(clientOptions));
    this.transcriptionClient = Suppliers.memoize(() -> new TranscriptionClient(clientOptions));
    this.translatedTtsClient = Suppliers.memoize(() -> new TranslatedTtsClient(clientOptions));
    this.streamingClient = Suppliers.memoize(() -> new StreamingClient(clientOptions));
    this.voiceCloningClient = Suppliers.memoize(() -> new VoiceCloningClient(clientOptions));
    this.dictionariesClient = Suppliers.memoize(() -> new DictionariesClient(clientOptions));
    this.projectSetupClient = Suppliers.memoize(() -> new ProjectSetupClient(clientOptions));
    this.deprecatedStreamingClient = Suppliers.memoize(() -> new DeprecatedStreamingClient(clientOptions));
  }

  public Object getSwaggerDocsDocsGet() {
    return getSwaggerDocsDocsGet(null);
  }

  public Object getSwaggerDocsDocsGet(RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("docs")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
    }
    catch (IOException e) {
      throw new CambApiException("Network error executing HTTP request", e);
    }
  }

  public Object getRedocDocsRedocsGet() {
    return getRedocDocsRedocsGet(null);
  }

  public Object getRedocDocsRedocsGet(RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("redocs")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
    }
    catch (IOException e) {
      throw new CambApiException("Network error executing HTTP request", e);
    }
  }

  public Object getOpenapiSchemaOpenapiJsonGet() {
    return getOpenapiSchemaOpenapiJsonGet(null);
  }

  public Object getOpenapiSchemaOpenapiJsonGet(RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("openapi.json")
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      if (response.isSuccessful()) {
        return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class);
      }
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
    }
    catch (IOException e) {
      throw new CambApiException("Network error executing HTTP request", e);
    }
  }

  public AudioSeparationClient audioSeparation() {
    return this.audioSeparationClient.get();
  }

  public DubClient dub() {
    return this.dubClient.get();
  }

  public FoldersClient folders() {
    return this.foldersClient.get();
  }

  public LanguagesClient languages() {
    return this.languagesClient.get();
  }

  public StoryClient story() {
    return this.storyClient.get();
  }

  public TranslatedStoryClient translatedStory() {
    return this.translatedStoryClient.get();
  }

  public TextToAudioClient textToAudio() {
    return this.textToAudioClient.get();
  }

  public TextToVoiceClient textToVoice() {
    return this.textToVoiceClient.get();
  }

  public TextToSpeechClient textToSpeech() {
    return this.textToSpeechClient.get();
  }

  public TranslationClient translation() {
    return this.translationClient.get();
  }

  public TranscriptionClient transcription() {
    return this.transcriptionClient.get();
  }

  public TranslatedTtsClient translatedTts() {
    return this.translatedTtsClient.get();
  }

  public StreamingClient streaming() {
    return this.streamingClient.get();
  }

  public VoiceCloningClient voiceCloning() {
    return this.voiceCloningClient.get();
  }

  public DictionariesClient dictionaries() {
    return this.dictionariesClient.get();
  }

  public ProjectSetupClient projectSetup() {
    return this.projectSetupClient.get();
  }

  public DeprecatedStreamingClient deprecatedStreaming() {
    return this.deprecatedStreamingClient.get();
  }

  public static CambApiClientBuilder builder() {
    return new CambApiClientBuilder();
  }
}
