/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.transcription.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BodyCreateTranscriptionTranscribePost.Builder.class
)
public final class BodyCreateTranscriptionTranscribePost {
  private final Optional<Integer> runId;

  private final int language;

  private final Optional<String> mediaUrl;

  private final Optional<String> audioUrl;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final Map<String, Object> additionalProperties;

  private BodyCreateTranscriptionTranscribePost(Optional<Integer> runId, int language,
      Optional<String> mediaUrl, Optional<String> audioUrl, Optional<String> projectName,
      Optional<String> projectDescription, Optional<Integer> folderId,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.language = language;
    this.mediaUrl = mediaUrl;
    this.audioUrl = audioUrl;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  /**
   * @return Signed URL to audio file for transcription
   */
  @JsonProperty("language")
  public int getLanguage() {
    return language;
  }

  /**
   * @return Signed URL to media file for transcription
   */
  @JsonProperty("media_url")
  public Optional<String> getMediaUrl() {
    return mediaUrl;
  }

  /**
   * @return [DEPRECATED] Use 'audio_url' instead
   */
  @JsonProperty("audio_url")
  public Optional<String> getAudioUrl() {
    return audioUrl;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BodyCreateTranscriptionTranscribePost && equalTo((BodyCreateTranscriptionTranscribePost) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BodyCreateTranscriptionTranscribePost other) {
    return runId.equals(other.runId) && language == other.language && mediaUrl.equals(other.mediaUrl) && audioUrl.equals(other.audioUrl) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.language, this.mediaUrl, this.audioUrl, this.projectName, this.projectDescription, this.folderId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static LanguageStage builder() {
    return new Builder();
  }

  public interface LanguageStage {
    _FinalStage language(int language);

    Builder from(BodyCreateTranscriptionTranscribePost other);
  }

  public interface _FinalStage {
    BodyCreateTranscriptionTranscribePost build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage mediaUrl(Optional<String> mediaUrl);

    _FinalStage mediaUrl(String mediaUrl);

    _FinalStage audioUrl(Optional<String> audioUrl);

    _FinalStage audioUrl(String audioUrl);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements LanguageStage, _FinalStage {
    private int language;

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<String> audioUrl = Optional.empty();

    private Optional<String> mediaUrl = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BodyCreateTranscriptionTranscribePost other) {
      runId(other.getRunId());
      language(other.getLanguage());
      mediaUrl(other.getMediaUrl());
      audioUrl(other.getAudioUrl());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      return this;
    }

    /**
     * <p>Signed URL to audio file for transcription</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("language")
    public _FinalStage language(int language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    /**
     * <p>[DEPRECATED] Use 'audio_url' instead</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage audioUrl(String audioUrl) {
      this.audioUrl = Optional.ofNullable(audioUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioUrl(Optional<String> audioUrl) {
      this.audioUrl = audioUrl;
      return this;
    }

    /**
     * <p>Signed URL to media file for transcription</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage mediaUrl(String mediaUrl) {
      this.mediaUrl = Optional.ofNullable(mediaUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "media_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage mediaUrl(Optional<String> mediaUrl) {
      this.mediaUrl = mediaUrl;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public BodyCreateTranscriptionTranscribePost build() {
      return new BodyCreateTranscriptionTranscribePost(runId, language, mediaUrl, audioUrl, projectName, projectDescription, folderId, additionalProperties);
    }
  }
}
