/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dictionaries.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import types.TermTranslationInput;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AddDictionaryTermPayload.Builder.class
)
public final class AddDictionaryTermPayload {
  private final Optional<Integer> runId;

  private final List<TermTranslationInput> translations;

  private final Map<String, Object> additionalProperties;

  private AddDictionaryTermPayload(Optional<Integer> runId, List<TermTranslationInput> translations,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.translations = translations;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("translations")
  public List<TermTranslationInput> getTranslations() {
    return translations;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AddDictionaryTermPayload && equalTo((AddDictionaryTermPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AddDictionaryTermPayload other) {
    return runId.equals(other.runId) && translations.equals(other.translations);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.translations);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> runId = Optional.empty();

    private List<TermTranslationInput> translations = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AddDictionaryTermPayload other) {
      runId(other.getRunId());
      translations(other.getTranslations());
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @JsonSetter(
        value = "translations",
        nulls = Nulls.SKIP
    )
    public Builder translations(List<TermTranslationInput> translations) {
      this.translations.clear();
      this.translations.addAll(translations);
      return this;
    }

    public Builder addTranslations(TermTranslationInput translations) {
      this.translations.add(translations);
      return this;
    }

    public Builder addAllTranslations(List<TermTranslationInput> translations) {
      this.translations.addAll(translations);
      return this;
    }

    public AddDictionaryTermPayload build() {
      return new AddDictionaryTermPayload(runId, translations, additionalProperties);
    }
  }
}
