/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dictionaries.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest.Builder.class
)
public final class GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest {
  private final Optional<Integer> limit;

  private final Optional<String> searchTerm;

  private final Optional<Integer> runId;

  private final Map<String, Object> additionalProperties;

  private GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest(Optional<Integer> limit,
      Optional<String> searchTerm, Optional<Integer> runId,
      Map<String, Object> additionalProperties) {
    this.limit = limit;
    this.searchTerm = searchTerm;
    this.runId = runId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Limit how many terms are returned when fetching the dictionary details.
   */
  @JsonProperty("limit")
  public Optional<Integer> getLimit() {
    return limit;
  }

  @JsonProperty("search_term")
  public Optional<String> getSearchTerm() {
    return searchTerm;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest && equalTo((GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest other) {
    return limit.equals(other.limit) && searchTerm.equals(other.searchTerm) && runId.equals(other.runId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.limit, this.searchTerm, this.runId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> limit = Optional.empty();

    private Optional<String> searchTerm = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest other) {
      limit(other.getLimit());
      searchTerm(other.getSearchTerm());
      runId(other.getRunId());
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Integer> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Integer limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    @JsonSetter(
        value = "search_term",
        nulls = Nulls.SKIP
    )
    public Builder searchTerm(Optional<String> searchTerm) {
      this.searchTerm = searchTerm;
      return this;
    }

    public Builder searchTerm(String searchTerm) {
      this.searchTerm = Optional.ofNullable(searchTerm);
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    public GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest build() {
      return new GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest(limit, searchTerm, runId, additionalProperties);
    }
  }
}
