/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.projectsetup;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.projectsetup.requests.CreateProjectSetupRequestPayload;
import resources.projectsetup.requests.CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest;
import resources.projectsetup.requests.GetProjectSetupResultProjectSetupResultRunIdGetRequest;
import resources.projectsetup.requests.GetProjectSetupRunsResultsProjectSetupResultsPostRequest;
import types.CreateProjectSetupOut;
import types.GetCreateProjectSetupResponse;
import types.HttpValidationError;

public class ProjectSetupClient {
  protected final ClientOptions clientOptions;

  public ProjectSetupClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Creates a new project setup with transcription capabilities.
   * <p>This endpoint allows users to create a new project by providing media content
   * (either as a file upload or URL), specifying source and target languages, and
   * other project metadata. The function validates inputs, checks file size limitations,
   * and initiates the project setup process.</p>
   * <p>Args:
   * request_payload (CreateProjectSetupRequestPayload): Complete project configuration
   * including media URL, source/target languages, project metadata, and
   * processing preferences such as audio track selection and dictionary choices.
   * api_key_obj_and_subscription: Dependency injection providing validated API key
   * object and associated subscription details for authorization and usage
   * limit enforcement.
   * traceparent (str | None, optional): OpenTelemetry trace parent header for
   * distributed tracing across microservices. Enables request correlation
   * and performance monitoring throughout the processing pipeline.</p>
   * <p>Returns:
   * Project setup response with project details and processing status.</p>
   * <p>Raises:
   * HTTPException:
   * - 400: If neither media_file nor media_url is provided
   * - 400: If uploaded file has no filename
   * - 413: If uploaded file exceeds size limit</p>
   */
  public CreateProjectSetupOut createProject(CreateProjectSetupRequestPayload request) {
    return createProject(request,null);
  }

  /**
   * Creates a new project setup with transcription capabilities.
   * <p>This endpoint allows users to create a new project by providing media content
   * (either as a file upload or URL), specifying source and target languages, and
   * other project metadata. The function validates inputs, checks file size limitations,
   * and initiates the project setup process.</p>
   * <p>Args:
   * request_payload (CreateProjectSetupRequestPayload): Complete project configuration
   * including media URL, source/target languages, project metadata, and
   * processing preferences such as audio track selection and dictionary choices.
   * api_key_obj_and_subscription: Dependency injection providing validated API key
   * object and associated subscription details for authorization and usage
   * limit enforcement.
   * traceparent (str | None, optional): OpenTelemetry trace parent header for
   * distributed tracing across microservices. Enables request correlation
   * and performance monitoring throughout the processing pipeline.</p>
   * <p>Returns:
   * Project setup response with project details and processing status.</p>
   * <p>Raises:
   * HTTPException:
   * - 400: If neither media_file nor media_url is provided
   * - 400: If uploaded file has no filename
   * - 413: If uploaded file exceeds size limit</p>
   */
  public CreateProjectSetupOut createProject(CreateProjectSetupRequestPayload request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("project-setup");if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("media_url", request.getMediaUrl());
      properties.put("source_language", request.getSourceLanguage());
      properties.put("target_languages", request.getTargetLanguages());
      if (request.getSelectedAudioTracks().isPresent()) {
        properties.put("selected_audio_tracks", request.getSelectedAudioTracks());
      }
      if (request.getAddOutputAsAnAudioTrack().isPresent()) {
        properties.put("add_output_as_an_audio_track", request.getAddOutputAsAnAudioTrack());
      }
      if (request.getChosenDictionaries().isPresent()) {
        properties.put("chosen_dictionaries", request.getChosenDictionaries());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateProjectSetupOut.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public List<GetCreateProjectSetupResponse> createProjectSetupTaskStatus(String taskId) {
      return createProjectSetupTaskStatus(taskId,CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest.builder().build());
    }

    public List<GetCreateProjectSetupResponse> createProjectSetupTaskStatus(String taskId,
        CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest request) {
      return createProjectSetupTaskStatus(taskId,request,null);
    }

    public List<GetCreateProjectSetupResponse> createProjectSetupTaskStatus(String taskId,
        CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("project-setup")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<GetCreateProjectSetupResponse>>() {});
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Retrieves the final result of a completed project setup.
       * <p>This endpoint provides access to the final results of a completed project setup.
       * It verifies that the authenticated user has access to the requested run_id and
       * validates that the run is of the correct type (<code>DUB_PROJECT</code>) before returning results.</p>
       * <p>Note:
       * This endpoint should only be called by users to retrieve their run results via API.
       * Access validation is performed to ensure users can only access their own runs.</p>
       * <p>Args:
       * run_id: Positive integer ID of the project setup run.
       * api_key_obj: API key authentication data from dependency.
       * traceparent: OpenTelemetry trace header for distributed tracing.</p>
       * <p>Returns:
       * GetCreateProjectSetupResponse: Project setup results including run details.</p>
       * <p>Raises:
       * HTTPException:
       * - 404: If the run_id is not found
       * - 400: If the run type is not valid for this endpoint (must be DUB_PROJECT)</p>
       */
      public Optional<GetCreateProjectSetupResponse> getProjectSetupResult(
          Optional<Integer> runId) {
        return getProjectSetupResult(runId,GetProjectSetupResultProjectSetupResultRunIdGetRequest.builder().build());
      }

      /**
       * Retrieves the final result of a completed project setup.
       * <p>This endpoint provides access to the final results of a completed project setup.
       * It verifies that the authenticated user has access to the requested run_id and
       * validates that the run is of the correct type (<code>DUB_PROJECT</code>) before returning results.</p>
       * <p>Note:
       * This endpoint should only be called by users to retrieve their run results via API.
       * Access validation is performed to ensure users can only access their own runs.</p>
       * <p>Args:
       * run_id: Positive integer ID of the project setup run.
       * api_key_obj: API key authentication data from dependency.
       * traceparent: OpenTelemetry trace header for distributed tracing.</p>
       * <p>Returns:
       * GetCreateProjectSetupResponse: Project setup results including run details.</p>
       * <p>Raises:
       * HTTPException:
       * - 404: If the run_id is not found
       * - 400: If the run type is not valid for this endpoint (must be DUB_PROJECT)</p>
       */
      public Optional<GetCreateProjectSetupResponse> getProjectSetupResult(Optional<Integer> runId,
          GetProjectSetupResultProjectSetupResultRunIdGetRequest request) {
        return getProjectSetupResult(runId,request,null);
      }

      /**
       * Retrieves the final result of a completed project setup.
       * <p>This endpoint provides access to the final results of a completed project setup.
       * It verifies that the authenticated user has access to the requested run_id and
       * validates that the run is of the correct type (<code>DUB_PROJECT</code>) before returning results.</p>
       * <p>Note:
       * This endpoint should only be called by users to retrieve their run results via API.
       * Access validation is performed to ensure users can only access their own runs.</p>
       * <p>Args:
       * run_id: Positive integer ID of the project setup run.
       * api_key_obj: API key authentication data from dependency.
       * traceparent: OpenTelemetry trace header for distributed tracing.</p>
       * <p>Returns:
       * GetCreateProjectSetupResponse: Project setup results including run details.</p>
       * <p>Raises:
       * HTTPException:
       * - 404: If the run_id is not found
       * - 400: If the run type is not valid for this endpoint (must be DUB_PROJECT)</p>
       */
      public Optional<GetCreateProjectSetupResponse> getProjectSetupResult(Optional<Integer> runId,
          GetProjectSetupResultProjectSetupResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("project-setup-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Optional<GetCreateProjectSetupResponse>>() {});
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
          catch (IOException e) {
            throw new CambApiException("Network error executing HTTP request", e);
          }
        }

        public List<GetCreateProjectSetupResponse> getProjectSetupRunsResults(
            GetProjectSetupRunsResultsProjectSetupResultsPostRequest request) {
          return getProjectSetupRunsResults(request,null);
        }

        public List<GetCreateProjectSetupResponse> getProjectSetupRunsResults(
            GetProjectSetupRunsResultsProjectSetupResultsPostRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("project-setup-results");if (request.getRunId().isPresent()) {
              httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<GetCreateProjectSetupResponse>>() {});
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            }
            catch (IOException e) {
              throw new CambApiException("Network error executing HTTP request", e);
            }
          }
        }
