/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import resources.dub.types.DubbedOutputInAltFormatRequestPayloadOutputFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DubbedOutputInAltFormatRequestPayload.Builder.class
)
public final class DubbedOutputInAltFormatRequestPayload {
  private final DubbedOutputInAltFormatRequestPayloadOutputFormat outputFormat;

  private final Map<String, Object> additionalProperties;

  private DubbedOutputInAltFormatRequestPayload(
      DubbedOutputInAltFormatRequestPayloadOutputFormat outputFormat,
      Map<String, Object> additionalProperties) {
    this.outputFormat = outputFormat;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("output_format")
  public DubbedOutputInAltFormatRequestPayloadOutputFormat getOutputFormat() {
    return outputFormat;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DubbedOutputInAltFormatRequestPayload && equalTo((DubbedOutputInAltFormatRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DubbedOutputInAltFormatRequestPayload other) {
    return outputFormat.equals(other.outputFormat);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.outputFormat);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OutputFormatStage builder() {
    return new Builder();
  }

  public interface OutputFormatStage {
    _FinalStage outputFormat(
        @NotNull DubbedOutputInAltFormatRequestPayloadOutputFormat outputFormat);

    Builder from(DubbedOutputInAltFormatRequestPayload other);
  }

  public interface _FinalStage {
    DubbedOutputInAltFormatRequestPayload build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OutputFormatStage, _FinalStage {
    private DubbedOutputInAltFormatRequestPayloadOutputFormat outputFormat;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DubbedOutputInAltFormatRequestPayload other) {
      outputFormat(other.getOutputFormat());
      return this;
    }

    @java.lang.Override
    @JsonSetter("output_format")
    public _FinalStage outputFormat(
        @NotNull DubbedOutputInAltFormatRequestPayloadOutputFormat outputFormat) {
      this.outputFormat = Objects.requireNonNull(outputFormat, "outputFormat must not be null");
      return this;
    }

    @java.lang.Override
    public DubbedOutputInAltFormatRequestPayload build() {
      return new DubbedOutputInAltFormatRequestPayload(outputFormat, additionalProperties);
    }
  }
}
