/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = EndToEndDubbingRequestPayload.Builder.class
)
public final class EndToEndDubbingRequestPayload {
  private final Optional<Integer> runId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final String videoUrl;

  private final int sourceLanguage;

  private final Optional<Integer> targetLanguage;

  private final Optional<List<Integer>> targetLanguages;

  private final Optional<List<Integer>> selectedAudioTracks;

  private final Optional<Boolean> addOutputAsAnAudioTrack;

  private final Optional<List<Integer>> chosenDictionaries;

  private final Optional<Boolean> aiOptimization;

  private final Map<String, Object> additionalProperties;

  private EndToEndDubbingRequestPayload(Optional<Integer> runId, Optional<String> projectName,
      Optional<String> projectDescription, Optional<Integer> folderId, String videoUrl,
      int sourceLanguage, Optional<Integer> targetLanguage, Optional<List<Integer>> targetLanguages,
      Optional<List<Integer>> selectedAudioTracks, Optional<Boolean> addOutputAsAnAudioTrack,
      Optional<List<Integer>> chosenDictionaries, Optional<Boolean> aiOptimization,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.videoUrl = videoUrl;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguage = targetLanguage;
    this.targetLanguages = targetLanguages;
    this.selectedAudioTracks = selectedAudioTracks;
    this.addOutputAsAnAudioTrack = addOutputAsAnAudioTrack;
    this.chosenDictionaries = chosenDictionaries;
    this.aiOptimization = aiOptimization;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @JsonProperty("video_url")
  public String getVideoUrl() {
    return videoUrl;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_language")
  public Optional<Integer> getTargetLanguage() {
    return targetLanguage;
  }

  @JsonProperty("target_languages")
  public Optional<List<Integer>> getTargetLanguages() {
    return targetLanguages;
  }

  @JsonProperty("selected_audio_tracks")
  public Optional<List<Integer>> getSelectedAudioTracks() {
    return selectedAudioTracks;
  }

  @JsonProperty("add_output_as_an_audio_track")
  public Optional<Boolean> getAddOutputAsAnAudioTrack() {
    return addOutputAsAnAudioTrack;
  }

  @JsonProperty("chosen_dictionaries")
  public Optional<List<Integer>> getChosenDictionaries() {
    return chosenDictionaries;
  }

  @JsonProperty("ai_optimization")
  public Optional<Boolean> getAiOptimization() {
    return aiOptimization;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof EndToEndDubbingRequestPayload && equalTo((EndToEndDubbingRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(EndToEndDubbingRequestPayload other) {
    return runId.equals(other.runId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId) && videoUrl.equals(other.videoUrl) && sourceLanguage == other.sourceLanguage && targetLanguage.equals(other.targetLanguage) && targetLanguages.equals(other.targetLanguages) && selectedAudioTracks.equals(other.selectedAudioTracks) && addOutputAsAnAudioTrack.equals(other.addOutputAsAnAudioTrack) && chosenDictionaries.equals(other.chosenDictionaries) && aiOptimization.equals(other.aiOptimization);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.projectName, this.projectDescription, this.folderId, this.videoUrl, this.sourceLanguage, this.targetLanguage, this.targetLanguages, this.selectedAudioTracks, this.addOutputAsAnAudioTrack, this.chosenDictionaries, this.aiOptimization);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static VideoUrlStage builder() {
    return new Builder();
  }

  public interface VideoUrlStage {
    SourceLanguageStage videoUrl(@NotNull String videoUrl);

    Builder from(EndToEndDubbingRequestPayload other);
  }

  public interface SourceLanguageStage {
    _FinalStage sourceLanguage(int sourceLanguage);
  }

  public interface _FinalStage {
    EndToEndDubbingRequestPayload build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage targetLanguage(Optional<Integer> targetLanguage);

    _FinalStage targetLanguage(Integer targetLanguage);

    _FinalStage targetLanguages(Optional<List<Integer>> targetLanguages);

    _FinalStage targetLanguages(List<Integer> targetLanguages);

    _FinalStage selectedAudioTracks(Optional<List<Integer>> selectedAudioTracks);

    _FinalStage selectedAudioTracks(List<Integer> selectedAudioTracks);

    _FinalStage addOutputAsAnAudioTrack(Optional<Boolean> addOutputAsAnAudioTrack);

    _FinalStage addOutputAsAnAudioTrack(Boolean addOutputAsAnAudioTrack);

    _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries);

    _FinalStage chosenDictionaries(List<Integer> chosenDictionaries);

    _FinalStage aiOptimization(Optional<Boolean> aiOptimization);

    _FinalStage aiOptimization(Boolean aiOptimization);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements VideoUrlStage, SourceLanguageStage, _FinalStage {
    private String videoUrl;

    private int sourceLanguage;

    private Optional<Boolean> aiOptimization = Optional.empty();

    private Optional<List<Integer>> chosenDictionaries = Optional.empty();

    private Optional<Boolean> addOutputAsAnAudioTrack = Optional.empty();

    private Optional<List<Integer>> selectedAudioTracks = Optional.empty();

    private Optional<List<Integer>> targetLanguages = Optional.empty();

    private Optional<Integer> targetLanguage = Optional.empty();

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(EndToEndDubbingRequestPayload other) {
      runId(other.getRunId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      videoUrl(other.getVideoUrl());
      sourceLanguage(other.getSourceLanguage());
      targetLanguage(other.getTargetLanguage());
      targetLanguages(other.getTargetLanguages());
      selectedAudioTracks(other.getSelectedAudioTracks());
      addOutputAsAnAudioTrack(other.getAddOutputAsAnAudioTrack());
      chosenDictionaries(other.getChosenDictionaries());
      aiOptimization(other.getAiOptimization());
      return this;
    }

    @java.lang.Override
    @JsonSetter("video_url")
    public SourceLanguageStage videoUrl(@NotNull String videoUrl) {
      this.videoUrl = Objects.requireNonNull(videoUrl, "videoUrl must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public _FinalStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    public _FinalStage aiOptimization(Boolean aiOptimization) {
      this.aiOptimization = Optional.ofNullable(aiOptimization);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "ai_optimization",
        nulls = Nulls.SKIP
    )
    public _FinalStage aiOptimization(Optional<Boolean> aiOptimization) {
      this.aiOptimization = aiOptimization;
      return this;
    }

    @java.lang.Override
    public _FinalStage chosenDictionaries(List<Integer> chosenDictionaries) {
      this.chosenDictionaries = Optional.ofNullable(chosenDictionaries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "chosen_dictionaries",
        nulls = Nulls.SKIP
    )
    public _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries) {
      this.chosenDictionaries = chosenDictionaries;
      return this;
    }

    @java.lang.Override
    public _FinalStage addOutputAsAnAudioTrack(Boolean addOutputAsAnAudioTrack) {
      this.addOutputAsAnAudioTrack = Optional.ofNullable(addOutputAsAnAudioTrack);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "add_output_as_an_audio_track",
        nulls = Nulls.SKIP
    )
    public _FinalStage addOutputAsAnAudioTrack(Optional<Boolean> addOutputAsAnAudioTrack) {
      this.addOutputAsAnAudioTrack = addOutputAsAnAudioTrack;
      return this;
    }

    @java.lang.Override
    public _FinalStage selectedAudioTracks(List<Integer> selectedAudioTracks) {
      this.selectedAudioTracks = Optional.ofNullable(selectedAudioTracks);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "selected_audio_tracks",
        nulls = Nulls.SKIP
    )
    public _FinalStage selectedAudioTracks(Optional<List<Integer>> selectedAudioTracks) {
      this.selectedAudioTracks = selectedAudioTracks;
      return this;
    }

    @java.lang.Override
    public _FinalStage targetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages = Optional.ofNullable(targetLanguages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetLanguages(Optional<List<Integer>> targetLanguages) {
      this.targetLanguages = targetLanguages;
      return this;
    }

    @java.lang.Override
    public _FinalStage targetLanguage(Integer targetLanguage) {
      this.targetLanguage = Optional.ofNullable(targetLanguage);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_language",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetLanguage(Optional<Integer> targetLanguage) {
      this.targetLanguage = targetLanguage;
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public EndToEndDubbingRequestPayload build() {
      return new EndToEndDubbingRequestPayload(runId, projectName, projectDescription, folderId, videoUrl, sourceLanguage, targetLanguage, targetLanguages, selectedAudioTracks, addOutputAsAnAudioTrack, chosenDictionaries, aiOptimization, additionalProperties);
    }
  }
}
