/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import types.TranscriptDataType;
import types.TranscriptFileFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest.Builder.class
)
public final class GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest {
  private final Optional<TranscriptFileFormat> formatType;

  private final Optional<TranscriptDataType> dataType;

  private final Map<String, Object> additionalProperties;

  private GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest(
      Optional<TranscriptFileFormat> formatType, Optional<TranscriptDataType> dataType,
      Map<String, Object> additionalProperties) {
    this.formatType = formatType;
    this.dataType = dataType;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Format to use for the transcription. Either <code>srt</code>, <code>vtt</code> or <code>txt</code>. Defaults to <code>txt</code>.
   */
  @JsonProperty("format_type")
  public Optional<TranscriptFileFormat> getFormatType() {
    return formatType;
  }

  /**
   * @return Data type for the transcription being returned. Returns the raw data of the transcription or a presigned url for the file that holds the transcription data.
   */
  @JsonProperty("data_type")
  public Optional<TranscriptDataType> getDataType() {
    return dataType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest && equalTo((GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest other) {
    return formatType.equals(other.formatType) && dataType.equals(other.dataType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.formatType, this.dataType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<TranscriptFileFormat> formatType = Optional.empty();

    private Optional<TranscriptDataType> dataType = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest other) {
      formatType(other.getFormatType());
      dataType(other.getDataType());
      return this;
    }

    @JsonSetter(
        value = "format_type",
        nulls = Nulls.SKIP
    )
    public Builder formatType(Optional<TranscriptFileFormat> formatType) {
      this.formatType = formatType;
      return this;
    }

    public Builder formatType(TranscriptFileFormat formatType) {
      this.formatType = Optional.ofNullable(formatType);
      return this;
    }

    @JsonSetter(
        value = "data_type",
        nulls = Nulls.SKIP
    )
    public Builder dataType(Optional<TranscriptDataType> dataType) {
      this.dataType = dataType;
      return this;
    }

    public Builder dataType(TranscriptDataType dataType) {
      this.dataType = Optional.ofNullable(dataType);
      return this;
    }

    public GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest build() {
      return new GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest(formatType, dataType, additionalProperties);
    }
  }
}
