/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.deprecatedstreaming.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.GetProbeStreamIn;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetProbeStreamV1StreamProbePostRequest.Builder.class
)
public final class GetProbeStreamV1StreamProbePostRequest {
  private final Optional<String> traceparent;

  private final Optional<Integer> runId;

  private final GetProbeStreamIn body;

  private final Map<String, Object> additionalProperties;

  private GetProbeStreamV1StreamProbePostRequest(Optional<String> traceparent,
      Optional<Integer> runId, GetProbeStreamIn body, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.runId = runId;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("traceparent")
  public Optional<String> getTraceparent() {
    return traceparent;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("body")
  public GetProbeStreamIn getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetProbeStreamV1StreamProbePostRequest && equalTo((GetProbeStreamV1StreamProbePostRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetProbeStreamV1StreamProbePostRequest other) {
    return traceparent.equals(other.traceparent) && runId.equals(other.runId) && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.runId, this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull GetProbeStreamIn body);

    Builder from(GetProbeStreamV1StreamProbePostRequest other);
  }

  public interface _FinalStage {
    GetProbeStreamV1StreamProbePostRequest build();

    _FinalStage traceparent(Optional<String> traceparent);

    _FinalStage traceparent(String traceparent);

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BodyStage, _FinalStage {
    private GetProbeStreamIn body;

    private Optional<Integer> runId = Optional.empty();

    private Optional<String> traceparent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetProbeStreamV1StreamProbePostRequest other) {
      traceparent(other.getTraceparent());
      runId(other.getRunId());
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull GetProbeStreamIn body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public _FinalStage traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    @java.lang.Override
    public GetProbeStreamV1StreamProbePostRequest build() {
      return new GetProbeStreamV1StreamProbePostRequest(traceparent, runId, body, additionalProperties);
    }
  }
}
