/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttoaudio.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.TextToAudioType;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTextToAudioRequestPayload.Builder.class
)
public final class CreateTextToAudioRequestPayload {
  private final Optional<String> traceparent;

  private final Optional<Integer> runId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final String prompt;

  private final Optional<Double> duration;

  private final Optional<TextToAudioType> audioType;

  private final Map<String, Object> additionalProperties;

  private CreateTextToAudioRequestPayload(Optional<String> traceparent, Optional<Integer> runId,
      Optional<String> projectName, Optional<String> projectDescription, Optional<Integer> folderId,
      String prompt, Optional<Double> duration, Optional<TextToAudioType> audioType,
      Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.runId = runId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.prompt = prompt;
    this.duration = duration;
    this.audioType = audioType;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("traceparent")
  public Optional<String> getTraceparent() {
    return traceparent;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  /**
   * @return The text to be converted to audio.
   */
  @JsonProperty("prompt")
  public String getPrompt() {
    return prompt;
  }

  /**
   * @return The desired duration of the audio.
   */
  @JsonProperty("duration")
  public Optional<Double> getDuration() {
    return duration;
  }

  /**
   * @return The audio type preference.
   */
  @JsonProperty("audio_type")
  public Optional<TextToAudioType> getAudioType() {
    return audioType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTextToAudioRequestPayload && equalTo((CreateTextToAudioRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTextToAudioRequestPayload other) {
    return traceparent.equals(other.traceparent) && runId.equals(other.runId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId) && prompt.equals(other.prompt) && duration.equals(other.duration) && audioType.equals(other.audioType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.runId, this.projectName, this.projectDescription, this.folderId, this.prompt, this.duration, this.audioType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PromptStage builder() {
    return new Builder();
  }

  public interface PromptStage {
    _FinalStage prompt(@NotNull String prompt);

    Builder from(CreateTextToAudioRequestPayload other);
  }

  public interface _FinalStage {
    CreateTextToAudioRequestPayload build();

    _FinalStage traceparent(Optional<String> traceparent);

    _FinalStage traceparent(String traceparent);

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage duration(Optional<Double> duration);

    _FinalStage duration(Double duration);

    _FinalStage audioType(Optional<TextToAudioType> audioType);

    _FinalStage audioType(TextToAudioType audioType);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PromptStage, _FinalStage {
    private String prompt;

    private Optional<TextToAudioType> audioType = Optional.empty();

    private Optional<Double> duration = Optional.empty();

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    private Optional<String> traceparent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTextToAudioRequestPayload other) {
      traceparent(other.getTraceparent());
      runId(other.getRunId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      prompt(other.getPrompt());
      duration(other.getDuration());
      audioType(other.getAudioType());
      return this;
    }

    /**
     * <p>The text to be converted to audio.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prompt")
    public _FinalStage prompt(@NotNull String prompt) {
      this.prompt = Objects.requireNonNull(prompt, "prompt must not be null");
      return this;
    }

    /**
     * <p>The audio type preference.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage audioType(TextToAudioType audioType) {
      this.audioType = Optional.ofNullable(audioType);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_type",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioType(Optional<TextToAudioType> audioType) {
      this.audioType = audioType;
      return this;
    }

    /**
     * <p>The desired duration of the audio.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage duration(Double duration) {
      this.duration = Optional.ofNullable(duration);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "duration",
        nulls = Nulls.SKIP
    )
    public _FinalStage duration(Optional<Double> duration) {
      this.duration = duration;
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public _FinalStage traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    @java.lang.Override
    public CreateTextToAudioRequestPayload build() {
      return new CreateTextToAudioRequestPayload(traceparent, runId, projectName, projectDescription, folderId, prompt, duration, audioType, additionalProperties);
    }
  }
}
