/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttoaudio.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetTextToAudioResultTextToSoundResultRunIdGetRequest.Builder.class
)
public final class GetTextToAudioResultTextToSoundResultRunIdGetRequest {
  private final Optional<String> outputType;

  private final Map<String, Object> additionalProperties;

  private GetTextToAudioResultTextToSoundResultRunIdGetRequest(Optional<String> outputType,
      Map<String, Object> additionalProperties) {
    this.outputType = outputType;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Output format for the Text To Speech result
   */
  @JsonProperty("output_type")
  public Optional<String> getOutputType() {
    return outputType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetTextToAudioResultTextToSoundResultRunIdGetRequest && equalTo((GetTextToAudioResultTextToSoundResultRunIdGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetTextToAudioResultTextToSoundResultRunIdGetRequest other) {
    return outputType.equals(other.outputType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.outputType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> outputType = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetTextToAudioResultTextToSoundResultRunIdGetRequest other) {
      outputType(other.getOutputType());
      return this;
    }

    @JsonSetter(
        value = "output_type",
        nulls = Nulls.SKIP
    )
    public Builder outputType(Optional<String> outputType) {
      this.outputType = outputType;
      return this;
    }

    public Builder outputType(String outputType) {
      this.outputType = Optional.ofNullable(outputType);
      return this;
    }

    public GetTextToAudioResultTextToSoundResultRunIdGetRequest build() {
      return new GetTextToAudioResultTextToSoundResultRunIdGetRequest(outputType, additionalProperties);
    }
  }
}
