/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.voicecloning;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.voicecloning.requests.BodyCreateCustomVoiceCreateCustomVoicePost;
import resources.voicecloning.requests.ListVoicesListVoicesGetRequest;
import resources.voicecloning.types.ListVoicesListVoicesGetResponseItem;
import types.CreateCustomVoiceOut;
import types.HttpValidationError;

public class VoiceCloningClient {
  protected final ClientOptions clientOptions;

  public VoiceCloningClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public List<ListVoicesListVoicesGetResponseItem> listVoices() {
    return listVoices(ListVoicesListVoicesGetRequest.builder().build());
  }

  public List<ListVoicesListVoicesGetResponseItem> listVoices(
      ListVoicesListVoicesGetRequest request) {
    return listVoices(request,null);
  }

  public List<ListVoicesListVoicesGetResponseItem> listVoices(
      ListVoicesListVoicesGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("list-voices");if (request.getRunId().isPresent()) {
        httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<ListVoicesListVoicesGetResponseItem>>() {});
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new CambApiException("Network error executing HTTP request", e);
      }
    }

    public CreateCustomVoiceOut createCustomVoice(File file,
        BodyCreateCustomVoiceCreateCustomVoicePost request) {
      return createCustomVoice(file,request,null);
    }

    public CreateCustomVoiceOut createCustomVoice(File file,
        BodyCreateCustomVoiceCreateCustomVoicePost request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("create-custom-voice");if (request.getRunId().isPresent()) {
          httpUrl.addQueryParameter("run_id", request.getRunId().get().toString());
        }
        MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
        try {
          body.addFormDataPart("voice_name", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getVoiceName()));
          body.addFormDataPart("gender", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getGender()));
          if (request.getDescription().isPresent()) {
            body.addFormDataPart("description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDescription()));
          }
          if (request.getPublishVoiceToMarketPlace().isPresent()) {
            body.addFormDataPart("publish_voice_to_market_place", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getPublishVoiceToMarketPlace()));
          }
          if (request.getAge().isPresent()) {
            body.addFormDataPart("age", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getAge()));
          }
          if (request.getLanguage().isPresent()) {
            body.addFormDataPart("language", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getLanguage()));
          }
          if (request.getEnhanceAudio().isPresent()) {
            body.addFormDataPart("enhance_audio", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getEnhanceAudio()));
          }
          String fileMimeType = Files.probeContentType(file.toPath());
          MediaType fileMimeTypeMediaType = fileMimeType != null ? MediaType.parse(fileMimeType) : null;
          body.addFormDataPart("file", file.getName(), RequestBody.create(fileMimeTypeMediaType, file));
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body.build())
          .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateCustomVoiceOut.class);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class));
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          throw new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        }
        catch (IOException e) {
          throw new CambApiException("Network error executing HTTP request", e);
        }
      }
    }
