/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AddTargetLanguageOut.Builder.class
)
public final class AddTargetLanguageOut {
  private final String message;

  private final Optional<String> taskId;

  private final Map<String, Object> additionalProperties;

  private AddTargetLanguageOut(String message, Optional<String> taskId,
      Map<String, Object> additionalProperties) {
    this.message = message;
    this.taskId = taskId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @JsonProperty("task_id")
  public Optional<String> getTaskId() {
    return taskId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AddTargetLanguageOut && equalTo((AddTargetLanguageOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AddTargetLanguageOut other) {
    return message.equals(other.message) && taskId.equals(other.taskId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.message, this.taskId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MessageStage builder() {
    return new Builder();
  }

  public interface MessageStage {
    _FinalStage message(@NotNull String message);

    Builder from(AddTargetLanguageOut other);
  }

  public interface _FinalStage {
    AddTargetLanguageOut build();

    _FinalStage taskId(Optional<String> taskId);

    _FinalStage taskId(String taskId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MessageStage, _FinalStage {
    private String message;

    private Optional<String> taskId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AddTargetLanguageOut other) {
      message(other.getMessage());
      taskId(other.getTaskId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("message")
    public _FinalStage message(@NotNull String message) {
      this.message = Objects.requireNonNull(message, "message must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage taskId(String taskId) {
      this.taskId = Optional.ofNullable(taskId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "task_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage taskId(Optional<String> taskId) {
      this.taskId = taskId;
      return this;
    }

    @java.lang.Override
    public AddTargetLanguageOut build() {
      return new AddTargetLanguageOut(message, taskId, additionalProperties);
    }
  }
}
