/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ConfigStreamPipeline.Builder.class
)
public final class ConfigStreamPipeline {
  private final Optional<DemixingOption> demixing;

  private final Optional<SegmentingOption> segmenting;

  private final Optional<TranscribingOption> transcribing;

  private final Optional<TranslatingOption> translating;

  private final Optional<RevoicingOption> revoicing;

  private final Map<String, Object> additionalProperties;

  private ConfigStreamPipeline(Optional<DemixingOption> demixing,
      Optional<SegmentingOption> segmenting, Optional<TranscribingOption> transcribing,
      Optional<TranslatingOption> translating, Optional<RevoicingOption> revoicing,
      Map<String, Object> additionalProperties) {
    this.demixing = demixing;
    this.segmenting = segmenting;
    this.transcribing = transcribing;
    this.translating = translating;
    this.revoicing = revoicing;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("demixing")
  public Optional<DemixingOption> getDemixing() {
    return demixing;
  }

  @JsonProperty("segmenting")
  public Optional<SegmentingOption> getSegmenting() {
    return segmenting;
  }

  @JsonProperty("transcribing")
  public Optional<TranscribingOption> getTranscribing() {
    return transcribing;
  }

  @JsonProperty("translating")
  public Optional<TranslatingOption> getTranslating() {
    return translating;
  }

  @JsonProperty("revoicing")
  public Optional<RevoicingOption> getRevoicing() {
    return revoicing;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ConfigStreamPipeline && equalTo((ConfigStreamPipeline) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ConfigStreamPipeline other) {
    return demixing.equals(other.demixing) && segmenting.equals(other.segmenting) && transcribing.equals(other.transcribing) && translating.equals(other.translating) && revoicing.equals(other.revoicing);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.demixing, this.segmenting, this.transcribing, this.translating, this.revoicing);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<DemixingOption> demixing = Optional.empty();

    private Optional<SegmentingOption> segmenting = Optional.empty();

    private Optional<TranscribingOption> transcribing = Optional.empty();

    private Optional<TranslatingOption> translating = Optional.empty();

    private Optional<RevoicingOption> revoicing = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ConfigStreamPipeline other) {
      demixing(other.getDemixing());
      segmenting(other.getSegmenting());
      transcribing(other.getTranscribing());
      translating(other.getTranslating());
      revoicing(other.getRevoicing());
      return this;
    }

    @JsonSetter(
        value = "demixing",
        nulls = Nulls.SKIP
    )
    public Builder demixing(Optional<DemixingOption> demixing) {
      this.demixing = demixing;
      return this;
    }

    public Builder demixing(DemixingOption demixing) {
      this.demixing = Optional.ofNullable(demixing);
      return this;
    }

    @JsonSetter(
        value = "segmenting",
        nulls = Nulls.SKIP
    )
    public Builder segmenting(Optional<SegmentingOption> segmenting) {
      this.segmenting = segmenting;
      return this;
    }

    public Builder segmenting(SegmentingOption segmenting) {
      this.segmenting = Optional.ofNullable(segmenting);
      return this;
    }

    @JsonSetter(
        value = "transcribing",
        nulls = Nulls.SKIP
    )
    public Builder transcribing(Optional<TranscribingOption> transcribing) {
      this.transcribing = transcribing;
      return this;
    }

    public Builder transcribing(TranscribingOption transcribing) {
      this.transcribing = Optional.ofNullable(transcribing);
      return this;
    }

    @JsonSetter(
        value = "translating",
        nulls = Nulls.SKIP
    )
    public Builder translating(Optional<TranslatingOption> translating) {
      this.translating = translating;
      return this;
    }

    public Builder translating(TranslatingOption translating) {
      this.translating = Optional.ofNullable(translating);
      return this;
    }

    @JsonSetter(
        value = "revoicing",
        nulls = Nulls.SKIP
    )
    public Builder revoicing(Optional<RevoicingOption> revoicing) {
      this.revoicing = revoicing;
      return this;
    }

    public Builder revoicing(RevoicingOption revoicing) {
      this.revoicing = Optional.ofNullable(revoicing);
      return this;
    }

    public ConfigStreamPipeline build() {
      return new ConfigStreamPipeline(demixing, segmenting, transcribing, translating, revoicing, additionalProperties);
    }
  }
}
