/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTtsOut.Builder.class
)
public final class CreateTtsOut {
  private final String taskId;

  private final Map<String, Object> additionalProperties;

  private CreateTtsOut(String taskId, Map<String, Object> additionalProperties) {
    this.taskId = taskId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("task_id")
  public String getTaskId() {
    return taskId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTtsOut && equalTo((CreateTtsOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTtsOut other) {
    return taskId.equals(other.taskId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.taskId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TaskIdStage builder() {
    return new Builder();
  }

  public interface TaskIdStage {
    _FinalStage taskId(@NotNull String taskId);

    Builder from(CreateTtsOut other);
  }

  public interface _FinalStage {
    CreateTtsOut build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TaskIdStage, _FinalStage {
    private String taskId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTtsOut other) {
      taskId(other.getTaskId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("task_id")
    public _FinalStage taskId(@NotNull String taskId) {
      this.taskId = Objects.requireNonNull(taskId, "taskId must not be null");
      return this;
    }

    @java.lang.Override
    public CreateTtsOut build() {
      return new CreateTtsOut(taskId, additionalProperties);
    }
  }
}
