/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateStreamRequestPayload.Builder.class
)
public final class CreateStreamRequestPayload {
  private final Optional<String> name;

  private final Optional<String> description;

  private final Optional<Integer> initialDelay;

  private final Optional<Integer> timeoutInMins;

  private final List<Integer> voices;

  private final List<Integer> dictionaries;

  private final ConfigStream config;

  private final SourceStream sourceStream;

  private final List<TargetStream> targetStreams;

  private final Optional<OffsetDateTime> startTime;

  private final Optional<OffsetDateTime> endTime;

  private final Optional<String> timezone;

  private final Map<String, Object> additionalProperties;

  private CreateStreamRequestPayload(Optional<String> name, Optional<String> description,
      Optional<Integer> initialDelay, Optional<Integer> timeoutInMins, List<Integer> voices,
      List<Integer> dictionaries, ConfigStream config, SourceStream sourceStream,
      List<TargetStream> targetStreams, Optional<OffsetDateTime> startTime,
      Optional<OffsetDateTime> endTime, Optional<String> timezone,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.description = description;
    this.initialDelay = initialDelay;
    this.timeoutInMins = timeoutInMins;
    this.voices = voices;
    this.dictionaries = dictionaries;
    this.config = config;
    this.sourceStream = sourceStream;
    this.targetStreams = targetStreams;
    this.startTime = startTime;
    this.endTime = endTime;
    this.timezone = timezone;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The name of the stream.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The description of the stream.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The initial delay in seconds before starting the stream creation process.
   */
  @JsonProperty("initial_delay")
  public Optional<Integer> getInitialDelay() {
    return initialDelay;
  }

  /**
   * @return The maximum duration in minutes for the stream creation process before timing out.
   */
  @JsonProperty("timeout_in_mins")
  public Optional<Integer> getTimeoutInMins() {
    return timeoutInMins;
  }

  /**
   * @return List of voice identifiers to be used in the stream.
   */
  @JsonProperty("voices")
  public List<Integer> getVoices() {
    return voices;
  }

  /**
   * @return List of dictionary identifiers to be used in the stream.
   */
  @JsonProperty("dictionaries")
  public List<Integer> getDictionaries() {
    return dictionaries;
  }

  /**
   * @return The shared configuration for the streaming pipeline.
   */
  @JsonProperty("config")
  public ConfigStream getConfig() {
    return config;
  }

  /**
   * @return The source stream configuration details.
   */
  @JsonProperty("source_stream")
  public SourceStream getSourceStream() {
    return sourceStream;
  }

  /**
   * @return List of target stream configurations.
   */
  @JsonProperty("target_streams")
  public List<TargetStream> getTargetStreams() {
    return targetStreams;
  }

  @JsonProperty("start_time")
  public Optional<OffsetDateTime> getStartTime() {
    return startTime;
  }

  @JsonProperty("end_time")
  public Optional<OffsetDateTime> getEndTime() {
    return endTime;
  }

  @JsonProperty("timezone")
  public Optional<String> getTimezone() {
    return timezone;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateStreamRequestPayload && equalTo((CreateStreamRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateStreamRequestPayload other) {
    return name.equals(other.name) && description.equals(other.description) && initialDelay.equals(other.initialDelay) && timeoutInMins.equals(other.timeoutInMins) && voices.equals(other.voices) && dictionaries.equals(other.dictionaries) && config.equals(other.config) && sourceStream.equals(other.sourceStream) && targetStreams.equals(other.targetStreams) && startTime.equals(other.startTime) && endTime.equals(other.endTime) && timezone.equals(other.timezone);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.description, this.initialDelay, this.timeoutInMins, this.voices, this.dictionaries, this.config, this.sourceStream, this.targetStreams, this.startTime, this.endTime, this.timezone);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ConfigStage builder() {
    return new Builder();
  }

  public interface ConfigStage {
    SourceStreamStage config(@NotNull ConfigStream config);

    Builder from(CreateStreamRequestPayload other);
  }

  public interface SourceStreamStage {
    _FinalStage sourceStream(@NotNull SourceStream sourceStream);
  }

  public interface _FinalStage {
    CreateStreamRequestPayload build();

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage initialDelay(Optional<Integer> initialDelay);

    _FinalStage initialDelay(Integer initialDelay);

    _FinalStage timeoutInMins(Optional<Integer> timeoutInMins);

    _FinalStage timeoutInMins(Integer timeoutInMins);

    _FinalStage voices(List<Integer> voices);

    _FinalStage addVoices(Integer voices);

    _FinalStage addAllVoices(List<Integer> voices);

    _FinalStage dictionaries(List<Integer> dictionaries);

    _FinalStage addDictionaries(Integer dictionaries);

    _FinalStage addAllDictionaries(List<Integer> dictionaries);

    _FinalStage targetStreams(List<TargetStream> targetStreams);

    _FinalStage addTargetStreams(TargetStream targetStreams);

    _FinalStage addAllTargetStreams(List<TargetStream> targetStreams);

    _FinalStage startTime(Optional<OffsetDateTime> startTime);

    _FinalStage startTime(OffsetDateTime startTime);

    _FinalStage endTime(Optional<OffsetDateTime> endTime);

    _FinalStage endTime(OffsetDateTime endTime);

    _FinalStage timezone(Optional<String> timezone);

    _FinalStage timezone(String timezone);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ConfigStage, SourceStreamStage, _FinalStage {
    private ConfigStream config;

    private SourceStream sourceStream;

    private Optional<String> timezone = Optional.empty();

    private Optional<OffsetDateTime> endTime = Optional.empty();

    private Optional<OffsetDateTime> startTime = Optional.empty();

    private List<TargetStream> targetStreams = new ArrayList<>();

    private List<Integer> dictionaries = new ArrayList<>();

    private List<Integer> voices = new ArrayList<>();

    private Optional<Integer> timeoutInMins = Optional.empty();

    private Optional<Integer> initialDelay = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateStreamRequestPayload other) {
      name(other.getName());
      description(other.getDescription());
      initialDelay(other.getInitialDelay());
      timeoutInMins(other.getTimeoutInMins());
      voices(other.getVoices());
      dictionaries(other.getDictionaries());
      config(other.getConfig());
      sourceStream(other.getSourceStream());
      targetStreams(other.getTargetStreams());
      startTime(other.getStartTime());
      endTime(other.getEndTime());
      timezone(other.getTimezone());
      return this;
    }

    /**
     * <p>The shared configuration for the streaming pipeline.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("config")
    public SourceStreamStage config(@NotNull ConfigStream config) {
      this.config = Objects.requireNonNull(config, "config must not be null");
      return this;
    }

    /**
     * <p>The source stream configuration details.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("source_stream")
    public _FinalStage sourceStream(@NotNull SourceStream sourceStream) {
      this.sourceStream = Objects.requireNonNull(sourceStream, "sourceStream must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public _FinalStage timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    @java.lang.Override
    public _FinalStage endTime(OffsetDateTime endTime) {
      this.endTime = Optional.ofNullable(endTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "end_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage endTime(Optional<OffsetDateTime> endTime) {
      this.endTime = endTime;
      return this;
    }

    @java.lang.Override
    public _FinalStage startTime(OffsetDateTime startTime) {
      this.startTime = Optional.ofNullable(startTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "start_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage startTime(Optional<OffsetDateTime> startTime) {
      this.startTime = startTime;
      return this;
    }

    /**
     * <p>List of target stream configurations.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllTargetStreams(List<TargetStream> targetStreams) {
      this.targetStreams.addAll(targetStreams);
      return this;
    }

    /**
     * <p>List of target stream configurations.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addTargetStreams(TargetStream targetStreams) {
      this.targetStreams.add(targetStreams);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_streams",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetStreams(List<TargetStream> targetStreams) {
      this.targetStreams.clear();
      this.targetStreams.addAll(targetStreams);
      return this;
    }

    /**
     * <p>List of dictionary identifiers to be used in the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllDictionaries(List<Integer> dictionaries) {
      this.dictionaries.addAll(dictionaries);
      return this;
    }

    /**
     * <p>List of dictionary identifiers to be used in the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addDictionaries(Integer dictionaries) {
      this.dictionaries.add(dictionaries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "dictionaries",
        nulls = Nulls.SKIP
    )
    public _FinalStage dictionaries(List<Integer> dictionaries) {
      this.dictionaries.clear();
      this.dictionaries.addAll(dictionaries);
      return this;
    }

    /**
     * <p>List of voice identifiers to be used in the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllVoices(List<Integer> voices) {
      this.voices.addAll(voices);
      return this;
    }

    /**
     * <p>List of voice identifiers to be used in the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addVoices(Integer voices) {
      this.voices.add(voices);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "voices",
        nulls = Nulls.SKIP
    )
    public _FinalStage voices(List<Integer> voices) {
      this.voices.clear();
      this.voices.addAll(voices);
      return this;
    }

    /**
     * <p>The maximum duration in minutes for the stream creation process before timing out.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeoutInMins(Integer timeoutInMins) {
      this.timeoutInMins = Optional.ofNullable(timeoutInMins);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "timeout_in_mins",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeoutInMins(Optional<Integer> timeoutInMins) {
      this.timeoutInMins = timeoutInMins;
      return this;
    }

    /**
     * <p>The initial delay in seconds before starting the stream creation process.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage initialDelay(Integer initialDelay) {
      this.initialDelay = Optional.ofNullable(initialDelay);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "initial_delay",
        nulls = Nulls.SKIP
    )
    public _FinalStage initialDelay(Optional<Integer> initialDelay) {
      this.initialDelay = initialDelay;
      return this;
    }

    /**
     * <p>The description of the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    /**
     * <p>The name of the stream.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public CreateStreamRequestPayload build() {
      return new CreateStreamRequestPayload(name, description, initialDelay, timeoutInMins, voices, dictionaries, config, sourceStream, targetStreams, startTime, endTime, timezone, additionalProperties);
    }
  }
}
