/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateCustomVoiceOut.Builder.class
)
public final class CreateCustomVoiceOut {
  private final int voiceId;

  private final Map<String, Object> additionalProperties;

  private CreateCustomVoiceOut(int voiceId, Map<String, Object> additionalProperties) {
    this.voiceId = voiceId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("voice_id")
  public int getVoiceId() {
    return voiceId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateCustomVoiceOut && equalTo((CreateCustomVoiceOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateCustomVoiceOut other) {
    return voiceId == other.voiceId;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.voiceId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static VoiceIdStage builder() {
    return new Builder();
  }

  public interface VoiceIdStage {
    _FinalStage voiceId(int voiceId);

    Builder from(CreateCustomVoiceOut other);
  }

  public interface _FinalStage {
    CreateCustomVoiceOut build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements VoiceIdStage, _FinalStage {
    private int voiceId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateCustomVoiceOut other) {
      voiceId(other.getVoiceId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("voice_id")
    public _FinalStage voiceId(int voiceId) {
      this.voiceId = voiceId;
      return this;
    }

    @java.lang.Override
    public CreateCustomVoiceOut build() {
      return new CreateCustomVoiceOut(voiceId, additionalProperties);
    }
  }
}
