/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum DemixingOption {
  NONE("none"),

  PICK_LEFT_CHANNEL("pick_left_channel"),

  PICK_RIGHT_CHANNEL("pick_right_channel"),

  PICK_CENTER_CHANNEL("pick_center_channel"),

  BEST_MODEL("best_model"),

  FAST_MODEL("fast_model");

  private final String value;

  DemixingOption(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
