/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DictionaryTerm.Builder.class
)
public final class DictionaryTerm {
  private final int id;

  private final List<TermTranslationOutput> termTranslations;

  private final Map<String, Object> additionalProperties;

  private DictionaryTerm(int id, List<TermTranslationOutput> termTranslations,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.termTranslations = termTranslations;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonProperty("term_translations")
  public List<TermTranslationOutput> getTermTranslations() {
    return termTranslations;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DictionaryTerm && equalTo((DictionaryTerm) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DictionaryTerm other) {
    return id == other.id && termTranslations.equals(other.termTranslations);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.termTranslations);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    _FinalStage id(int id);

    Builder from(DictionaryTerm other);
  }

  public interface _FinalStage {
    DictionaryTerm build();

    _FinalStage termTranslations(List<TermTranslationOutput> termTranslations);

    _FinalStage addTermTranslations(TermTranslationOutput termTranslations);

    _FinalStage addAllTermTranslations(List<TermTranslationOutput> termTranslations);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private int id;

    private List<TermTranslationOutput> termTranslations = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DictionaryTerm other) {
      id(other.getId());
      termTranslations(other.getTermTranslations());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(int id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllTermTranslations(List<TermTranslationOutput> termTranslations) {
      this.termTranslations.addAll(termTranslations);
      return this;
    }

    @java.lang.Override
    public _FinalStage addTermTranslations(TermTranslationOutput termTranslations) {
      this.termTranslations.add(termTranslations);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "term_translations",
        nulls = Nulls.SKIP
    )
    public _FinalStage termTranslations(List<TermTranslationOutput> termTranslations) {
      this.termTranslations.clear();
      this.termTranslations.addAll(termTranslations);
      return this;
    }

    @java.lang.Override
    public DictionaryTerm build() {
      return new DictionaryTerm(id, termTranslations, additionalProperties);
    }
  }
}
