/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DubbingResult.Builder.class
)
public final class DubbingResult {
  private final String audioUrl;

  private final List<Transcript> transcript;

  private final Optional<String> videoUrl;

  private final Map<String, Object> additionalProperties;

  private DubbingResult(String audioUrl, List<Transcript> transcript, Optional<String> videoUrl,
      Map<String, Object> additionalProperties) {
    this.audioUrl = audioUrl;
    this.transcript = transcript;
    this.videoUrl = videoUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("audio_url")
  public String getAudioUrl() {
    return audioUrl;
  }

  @JsonProperty("transcript")
  public List<Transcript> getTranscript() {
    return transcript;
  }

  @JsonProperty("video_url")
  public Optional<String> getVideoUrl() {
    return videoUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DubbingResult && equalTo((DubbingResult) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DubbingResult other) {
    return audioUrl.equals(other.audioUrl) && transcript.equals(other.transcript) && videoUrl.equals(other.videoUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.audioUrl, this.transcript, this.videoUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AudioUrlStage builder() {
    return new Builder();
  }

  public interface AudioUrlStage {
    _FinalStage audioUrl(@NotNull String audioUrl);

    Builder from(DubbingResult other);
  }

  public interface _FinalStage {
    DubbingResult build();

    _FinalStage transcript(List<Transcript> transcript);

    _FinalStage addTranscript(Transcript transcript);

    _FinalStage addAllTranscript(List<Transcript> transcript);

    _FinalStage videoUrl(Optional<String> videoUrl);

    _FinalStage videoUrl(String videoUrl);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AudioUrlStage, _FinalStage {
    private String audioUrl;

    private Optional<String> videoUrl = Optional.empty();

    private List<Transcript> transcript = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DubbingResult other) {
      audioUrl(other.getAudioUrl());
      transcript(other.getTranscript());
      videoUrl(other.getVideoUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("audio_url")
    public _FinalStage audioUrl(@NotNull String audioUrl) {
      this.audioUrl = Objects.requireNonNull(audioUrl, "audioUrl must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage videoUrl(String videoUrl) {
      this.videoUrl = Optional.ofNullable(videoUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "video_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage videoUrl(Optional<String> videoUrl) {
      this.videoUrl = videoUrl;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllTranscript(List<Transcript> transcript) {
      this.transcript.addAll(transcript);
      return this;
    }

    @java.lang.Override
    public _FinalStage addTranscript(Transcript transcript) {
      this.transcript.add(transcript);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "transcript",
        nulls = Nulls.SKIP
    )
    public _FinalStage transcript(List<Transcript> transcript) {
      this.transcript.clear();
      this.transcript.addAll(transcript);
      return this;
    }

    @java.lang.Override
    public DubbingResult build() {
      return new DubbingResult(audioUrl, transcript, videoUrl, additionalProperties);
    }
  }
}
