/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAudioSeparationResultOut.Builder.class
)
public final class GetAudioSeparationResultOut {
  private final String foregroundAudioUrl;

  private final String backgroundAudioUrl;

  private final Map<String, Object> additionalProperties;

  private GetAudioSeparationResultOut(String foregroundAudioUrl, String backgroundAudioUrl,
      Map<String, Object> additionalProperties) {
    this.foregroundAudioUrl = foregroundAudioUrl;
    this.backgroundAudioUrl = backgroundAudioUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("foreground_audio_url")
  public String getForegroundAudioUrl() {
    return foregroundAudioUrl;
  }

  @JsonProperty("background_audio_url")
  public String getBackgroundAudioUrl() {
    return backgroundAudioUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAudioSeparationResultOut && equalTo((GetAudioSeparationResultOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAudioSeparationResultOut other) {
    return foregroundAudioUrl.equals(other.foregroundAudioUrl) && backgroundAudioUrl.equals(other.backgroundAudioUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.foregroundAudioUrl, this.backgroundAudioUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ForegroundAudioUrlStage builder() {
    return new Builder();
  }

  public interface ForegroundAudioUrlStage {
    BackgroundAudioUrlStage foregroundAudioUrl(@NotNull String foregroundAudioUrl);

    Builder from(GetAudioSeparationResultOut other);
  }

  public interface BackgroundAudioUrlStage {
    _FinalStage backgroundAudioUrl(@NotNull String backgroundAudioUrl);
  }

  public interface _FinalStage {
    GetAudioSeparationResultOut build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ForegroundAudioUrlStage, BackgroundAudioUrlStage, _FinalStage {
    private String foregroundAudioUrl;

    private String backgroundAudioUrl;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetAudioSeparationResultOut other) {
      foregroundAudioUrl(other.getForegroundAudioUrl());
      backgroundAudioUrl(other.getBackgroundAudioUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("foreground_audio_url")
    public BackgroundAudioUrlStage foregroundAudioUrl(@NotNull String foregroundAudioUrl) {
      this.foregroundAudioUrl = Objects.requireNonNull(foregroundAudioUrl, "foregroundAudioUrl must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("background_audio_url")
    public _FinalStage backgroundAudioUrl(@NotNull String backgroundAudioUrl) {
      this.backgroundAudioUrl = Objects.requireNonNull(backgroundAudioUrl, "backgroundAudioUrl must not be null");
      return this;
    }

    @java.lang.Override
    public GetAudioSeparationResultOut build() {
      return new GetAudioSeparationResultOut(foregroundAudioUrl, backgroundAudioUrl, additionalProperties);
    }
  }
}
