/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetCreateProjectSetupResponse.Builder.class
)
public final class GetCreateProjectSetupResponse {
  private final int runId;

  private final ProjectDetails projectDetails;

  private final Map<String, Object> additionalProperties;

  private GetCreateProjectSetupResponse(int runId, ProjectDetails projectDetails,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.projectDetails = projectDetails;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public int getRunId() {
    return runId;
  }

  @JsonProperty("project_details")
  public ProjectDetails getProjectDetails() {
    return projectDetails;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetCreateProjectSetupResponse && equalTo((GetCreateProjectSetupResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetCreateProjectSetupResponse other) {
    return runId == other.runId && projectDetails.equals(other.projectDetails);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.projectDetails);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RunIdStage builder() {
    return new Builder();
  }

  public interface RunIdStage {
    ProjectDetailsStage runId(int runId);

    Builder from(GetCreateProjectSetupResponse other);
  }

  public interface ProjectDetailsStage {
    _FinalStage projectDetails(@NotNull ProjectDetails projectDetails);
  }

  public interface _FinalStage {
    GetCreateProjectSetupResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RunIdStage, ProjectDetailsStage, _FinalStage {
    private int runId;

    private ProjectDetails projectDetails;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetCreateProjectSetupResponse other) {
      runId(other.getRunId());
      projectDetails(other.getProjectDetails());
      return this;
    }

    @java.lang.Override
    @JsonSetter("run_id")
    public ProjectDetailsStage runId(int runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    @JsonSetter("project_details")
    public _FinalStage projectDetails(@NotNull ProjectDetails projectDetails) {
      this.projectDetails = Objects.requireNonNull(projectDetails, "projectDetails must not be null");
      return this;
    }

    @java.lang.Override
    public GetCreateProjectSetupResponse build() {
      return new GetCreateProjectSetupResponse(runId, projectDetails, additionalProperties);
    }
  }
}
