/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetProbeStreamIn.Builder.class
)
public final class GetProbeStreamIn {
  private final String url;

  private final Optional<String> passphrase;

  private final Optional<String> streamId;

  private final Map<String, Object> additionalProperties;

  private GetProbeStreamIn(String url, Optional<String> passphrase, Optional<String> streamId,
      Map<String, Object> additionalProperties) {
    this.url = url;
    this.passphrase = passphrase;
    this.streamId = streamId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @JsonProperty("passphrase")
  public Optional<String> getPassphrase() {
    return passphrase;
  }

  @JsonProperty("stream_id")
  public Optional<String> getStreamId() {
    return streamId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetProbeStreamIn && equalTo((GetProbeStreamIn) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetProbeStreamIn other) {
    return url.equals(other.url) && passphrase.equals(other.passphrase) && streamId.equals(other.streamId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.url, this.passphrase, this.streamId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);

    Builder from(GetProbeStreamIn other);
  }

  public interface _FinalStage {
    GetProbeStreamIn build();

    _FinalStage passphrase(Optional<String> passphrase);

    _FinalStage passphrase(String passphrase);

    _FinalStage streamId(Optional<String> streamId);

    _FinalStage streamId(String streamId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private Optional<String> streamId = Optional.empty();

    private Optional<String> passphrase = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetProbeStreamIn other) {
      url(other.getUrl());
      passphrase(other.getPassphrase());
      streamId(other.getStreamId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage streamId(String streamId) {
      this.streamId = Optional.ofNullable(streamId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "stream_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage streamId(Optional<String> streamId) {
      this.streamId = streamId;
      return this;
    }

    @java.lang.Override
    public _FinalStage passphrase(String passphrase) {
      this.passphrase = Optional.ofNullable(passphrase);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "passphrase",
        nulls = Nulls.SKIP
    )
    public _FinalStage passphrase(Optional<String> passphrase) {
      this.passphrase = passphrase;
      return this;
    }

    @java.lang.Override
    public GetProbeStreamIn build() {
      return new GetProbeStreamIn(url, passphrase, streamId, additionalProperties);
    }
  }
}
