/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetSetupStoryResultResponse.Builder.class
)
public final class GetSetupStoryResultResponse {
  private final int runId;

  private final StoryDetails storyDetails;

  private final Map<String, Object> additionalProperties;

  private GetSetupStoryResultResponse(int runId, StoryDetails storyDetails,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.storyDetails = storyDetails;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public int getRunId() {
    return runId;
  }

  @JsonProperty("story_details")
  public StoryDetails getStoryDetails() {
    return storyDetails;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetSetupStoryResultResponse && equalTo((GetSetupStoryResultResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetSetupStoryResultResponse other) {
    return runId == other.runId && storyDetails.equals(other.storyDetails);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.storyDetails);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RunIdStage builder() {
    return new Builder();
  }

  public interface RunIdStage {
    StoryDetailsStage runId(int runId);

    Builder from(GetSetupStoryResultResponse other);
  }

  public interface StoryDetailsStage {
    _FinalStage storyDetails(@NotNull StoryDetails storyDetails);
  }

  public interface _FinalStage {
    GetSetupStoryResultResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RunIdStage, StoryDetailsStage, _FinalStage {
    private int runId;

    private StoryDetails storyDetails;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetSetupStoryResultResponse other) {
      runId(other.getRunId());
      storyDetails(other.getStoryDetails());
      return this;
    }

    @java.lang.Override
    @JsonSetter("run_id")
    public StoryDetailsStage runId(int runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    @JsonSetter("story_details")
    public _FinalStage storyDetails(@NotNull StoryDetails storyDetails) {
      this.storyDetails = Objects.requireNonNull(storyDetails, "storyDetails must not be null");
      return this;
    }

    @java.lang.Override
    public GetSetupStoryResultResponse build() {
      return new GetSetupStoryResultResponse(runId, storyDetails, additionalProperties);
    }
  }
}
