/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetTtsResultOutFileUrl.Builder.class
)
public final class GetTtsResultOutFileUrl {
  private final String outputUrl;

  private final Map<String, Object> additionalProperties;

  private GetTtsResultOutFileUrl(String outputUrl, Map<String, Object> additionalProperties) {
    this.outputUrl = outputUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("output_url")
  public String getOutputUrl() {
    return outputUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetTtsResultOutFileUrl && equalTo((GetTtsResultOutFileUrl) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetTtsResultOutFileUrl other) {
    return outputUrl.equals(other.outputUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.outputUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OutputUrlStage builder() {
    return new Builder();
  }

  public interface OutputUrlStage {
    _FinalStage outputUrl(@NotNull String outputUrl);

    Builder from(GetTtsResultOutFileUrl other);
  }

  public interface _FinalStage {
    GetTtsResultOutFileUrl build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OutputUrlStage, _FinalStage {
    private String outputUrl;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetTtsResultOutFileUrl other) {
      outputUrl(other.getOutputUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("output_url")
    public _FinalStage outputUrl(@NotNull String outputUrl) {
      this.outputUrl = Objects.requireNonNull(outputUrl, "outputUrl must not be null");
      return this;
    }

    @java.lang.Override
    public GetTtsResultOutFileUrl build() {
      return new GetTtsResultOutFileUrl(outputUrl, additionalProperties);
    }
  }
}
