/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetTextToVoiceResultOut.Builder.class
)
public final class GetTextToVoiceResultOut {
  private final List<String> previews;

  private final Map<String, Object> additionalProperties;

  private GetTextToVoiceResultOut(List<String> previews, Map<String, Object> additionalProperties) {
    this.previews = previews;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("previews")
  public List<String> getPreviews() {
    return previews;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetTextToVoiceResultOut && equalTo((GetTextToVoiceResultOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetTextToVoiceResultOut other) {
    return previews.equals(other.previews);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.previews);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<String> previews = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetTextToVoiceResultOut other) {
      previews(other.getPreviews());
      return this;
    }

    @JsonSetter(
        value = "previews",
        nulls = Nulls.SKIP
    )
    public Builder previews(List<String> previews) {
      this.previews.clear();
      this.previews.addAll(previews);
      return this;
    }

    public Builder addPreviews(String previews) {
      this.previews.add(previews);
      return this;
    }

    public Builder addAllPreviews(List<String> previews) {
      this.previews.addAll(previews);
      return this;
    }

    public GetTextToVoiceResultOut build() {
      return new GetTextToVoiceResultOut(previews, additionalProperties);
    }
  }
}
