/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LanguagePydanticModel.Builder.class
)
public final class LanguagePydanticModel {
  private final int id;

  private final String language;

  private final String shortName;

  private final Map<String, Object> additionalProperties;

  private LanguagePydanticModel(int id, String language, String shortName,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.language = language;
    this.shortName = shortName;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonProperty("language")
  public String getLanguage() {
    return language;
  }

  @JsonProperty("short_name")
  public String getShortName() {
    return shortName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LanguagePydanticModel && equalTo((LanguagePydanticModel) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LanguagePydanticModel other) {
    return id == other.id && language.equals(other.language) && shortName.equals(other.shortName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.language, this.shortName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    LanguageStage id(int id);

    Builder from(LanguagePydanticModel other);
  }

  public interface LanguageStage {
    ShortNameStage language(@NotNull String language);
  }

  public interface ShortNameStage {
    _FinalStage shortName(@NotNull String shortName);
  }

  public interface _FinalStage {
    LanguagePydanticModel build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, LanguageStage, ShortNameStage, _FinalStage {
    private int id;

    private String language;

    private String shortName;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LanguagePydanticModel other) {
      id(other.getId());
      language(other.getLanguage());
      shortName(other.getShortName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public LanguageStage id(int id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    @JsonSetter("language")
    public ShortNameStage language(@NotNull String language) {
      this.language = Objects.requireNonNull(language, "language must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("short_name")
    public _FinalStage shortName(@NotNull String shortName) {
      this.shortName = Objects.requireNonNull(shortName, "shortName must not be null");
      return this;
    }

    @java.lang.Override
    public LanguagePydanticModel build() {
      return new LanguagePydanticModel(id, language, shortName, additionalProperties);
    }
  }
}
