/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OrchestratorPipelineResult.Builder.class
)
public final class OrchestratorPipelineResult {
  private final TaskStatus status;

  private final Optional<Integer> runId;

  private final Optional<OrchestratorPipelineResultExceptionReason> exceptionReason;

  private final Optional<OrchestratorPipelineResultMessage> message;

  private final Map<String, Object> additionalProperties;

  private OrchestratorPipelineResult(TaskStatus status, Optional<Integer> runId,
      Optional<OrchestratorPipelineResultExceptionReason> exceptionReason,
      Optional<OrchestratorPipelineResultMessage> message,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.runId = runId;
    this.exceptionReason = exceptionReason;
    this.message = message;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public TaskStatus getStatus() {
    return status;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("exception_reason")
  public Optional<OrchestratorPipelineResultExceptionReason> getExceptionReason() {
    return exceptionReason;
  }

  @JsonProperty("message")
  public Optional<OrchestratorPipelineResultMessage> getMessage() {
    return message;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OrchestratorPipelineResult && equalTo((OrchestratorPipelineResult) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OrchestratorPipelineResult other) {
    return status.equals(other.status) && runId.equals(other.runId) && exceptionReason.equals(other.exceptionReason) && message.equals(other.message);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.runId, this.exceptionReason, this.message);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    _FinalStage status(@NotNull TaskStatus status);

    Builder from(OrchestratorPipelineResult other);
  }

  public interface _FinalStage {
    OrchestratorPipelineResult build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage exceptionReason(
        Optional<OrchestratorPipelineResultExceptionReason> exceptionReason);

    _FinalStage exceptionReason(OrchestratorPipelineResultExceptionReason exceptionReason);

    _FinalStage message(Optional<OrchestratorPipelineResultMessage> message);

    _FinalStage message(OrchestratorPipelineResultMessage message);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, _FinalStage {
    private TaskStatus status;

    private Optional<OrchestratorPipelineResultMessage> message = Optional.empty();

    private Optional<OrchestratorPipelineResultExceptionReason> exceptionReason = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(OrchestratorPipelineResult other) {
      status(other.getStatus());
      runId(other.getRunId());
      exceptionReason(other.getExceptionReason());
      message(other.getMessage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull TaskStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage message(OrchestratorPipelineResultMessage message) {
      this.message = Optional.ofNullable(message);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "message",
        nulls = Nulls.SKIP
    )
    public _FinalStage message(Optional<OrchestratorPipelineResultMessage> message) {
      this.message = message;
      return this;
    }

    @java.lang.Override
    public _FinalStage exceptionReason(OrchestratorPipelineResultExceptionReason exceptionReason) {
      this.exceptionReason = Optional.ofNullable(exceptionReason);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "exception_reason",
        nulls = Nulls.SKIP
    )
    public _FinalStage exceptionReason(
        Optional<OrchestratorPipelineResultExceptionReason> exceptionReason) {
      this.exceptionReason = exceptionReason;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public OrchestratorPipelineResult build() {
      return new OrchestratorPipelineResult(status, runId, exceptionReason, message, additionalProperties);
    }
  }
}
