/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OrchestratorPipelineCallResult.Builder.class
)
public final class OrchestratorPipelineCallResult {
  private final Optional<String> taskId;

  private final Map<String, Object> additionalProperties;

  private OrchestratorPipelineCallResult(Optional<String> taskId,
      Map<String, Object> additionalProperties) {
    this.taskId = taskId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("task_id")
  public Optional<String> getTaskId() {
    return taskId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OrchestratorPipelineCallResult && equalTo((OrchestratorPipelineCallResult) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OrchestratorPipelineCallResult other) {
    return taskId.equals(other.taskId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.taskId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> taskId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OrchestratorPipelineCallResult other) {
      taskId(other.getTaskId());
      return this;
    }

    @JsonSetter(
        value = "task_id",
        nulls = Nulls.SKIP
    )
    public Builder taskId(Optional<String> taskId) {
      this.taskId = taskId;
      return this;
    }

    public Builder taskId(String taskId) {
      this.taskId = Optional.ofNullable(taskId);
      return this;
    }

    public OrchestratorPipelineCallResult build() {
      return new OrchestratorPipelineCallResult(taskId, additionalProperties);
    }
  }
}
