/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum OutputFormat {
  WAV("wav"),

  FLAC("flac"),

  ADTS("adts"),

  MP3("mp3"),

  PCM_S16LE("pcm_s16le"),

  PCM_S16BE("pcm_s16be"),

  PCM_S32BE("pcm_s32be"),

  PCM_S32LE("pcm_s32le"),

  PCM_F32LE("pcm_f32le"),

  PCM_F32BE("pcm_f32be");

  private final String value;

  OutputFormat(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
