/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OverdubConfig.Builder.class
)
public final class OverdubConfig {
  private final Optional<Double> originalAudioGain;

  private final Optional<Double> backgroundAudioGain;

  private final Optional<Double> fadeTime;

  private final Optional<Double> fallbackAudioGain;

  private final Map<String, Object> additionalProperties;

  private OverdubConfig(Optional<Double> originalAudioGain, Optional<Double> backgroundAudioGain,
      Optional<Double> fadeTime, Optional<Double> fallbackAudioGain,
      Map<String, Object> additionalProperties) {
    this.originalAudioGain = originalAudioGain;
    this.backgroundAudioGain = backgroundAudioGain;
    this.fadeTime = fadeTime;
    this.fallbackAudioGain = fallbackAudioGain;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Proportion of the original audio (0.0 to 1.0).
   */
  @JsonProperty("original_audio_gain")
  public Optional<Double> getOriginalAudioGain() {
    return originalAudioGain;
  }

  /**
   * @return Proportion of the background audio (0.0 to 1.0).
   */
  @JsonProperty("background_audio_gain")
  public Optional<Double> getBackgroundAudioGain() {
    return backgroundAudioGain;
  }

  /**
   * @return Cross-fade duration in seconds (0.0 to 5.0).
   */
  @JsonProperty("fade_time")
  public Optional<Double> getFadeTime() {
    return fadeTime;
  }

  /**
   * @return Proportion of the fallback audio (0.0 to 1.0) (for streaming only).
   */
  @JsonProperty("fallback_audio_gain")
  public Optional<Double> getFallbackAudioGain() {
    return fallbackAudioGain;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OverdubConfig && equalTo((OverdubConfig) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OverdubConfig other) {
    return originalAudioGain.equals(other.originalAudioGain) && backgroundAudioGain.equals(other.backgroundAudioGain) && fadeTime.equals(other.fadeTime) && fallbackAudioGain.equals(other.fallbackAudioGain);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.originalAudioGain, this.backgroundAudioGain, this.fadeTime, this.fallbackAudioGain);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> originalAudioGain = Optional.empty();

    private Optional<Double> backgroundAudioGain = Optional.empty();

    private Optional<Double> fadeTime = Optional.empty();

    private Optional<Double> fallbackAudioGain = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OverdubConfig other) {
      originalAudioGain(other.getOriginalAudioGain());
      backgroundAudioGain(other.getBackgroundAudioGain());
      fadeTime(other.getFadeTime());
      fallbackAudioGain(other.getFallbackAudioGain());
      return this;
    }

    @JsonSetter(
        value = "original_audio_gain",
        nulls = Nulls.SKIP
    )
    public Builder originalAudioGain(Optional<Double> originalAudioGain) {
      this.originalAudioGain = originalAudioGain;
      return this;
    }

    public Builder originalAudioGain(Double originalAudioGain) {
      this.originalAudioGain = Optional.ofNullable(originalAudioGain);
      return this;
    }

    @JsonSetter(
        value = "background_audio_gain",
        nulls = Nulls.SKIP
    )
    public Builder backgroundAudioGain(Optional<Double> backgroundAudioGain) {
      this.backgroundAudioGain = backgroundAudioGain;
      return this;
    }

    public Builder backgroundAudioGain(Double backgroundAudioGain) {
      this.backgroundAudioGain = Optional.ofNullable(backgroundAudioGain);
      return this;
    }

    @JsonSetter(
        value = "fade_time",
        nulls = Nulls.SKIP
    )
    public Builder fadeTime(Optional<Double> fadeTime) {
      this.fadeTime = fadeTime;
      return this;
    }

    public Builder fadeTime(Double fadeTime) {
      this.fadeTime = Optional.ofNullable(fadeTime);
      return this;
    }

    @JsonSetter(
        value = "fallback_audio_gain",
        nulls = Nulls.SKIP
    )
    public Builder fallbackAudioGain(Optional<Double> fallbackAudioGain) {
      this.fallbackAudioGain = fallbackAudioGain;
      return this;
    }

    public Builder fallbackAudioGain(Double fallbackAudioGain) {
      this.fallbackAudioGain = Optional.ofNullable(fallbackAudioGain);
      return this;
    }

    public OverdubConfig build() {
      return new OverdubConfig(originalAudioGain, backgroundAudioGain, fadeTime, fallbackAudioGain, additionalProperties);
    }
  }
}
