/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ProjectDetails.Builder.class
)
public final class ProjectDetails {
  private final String projectName;

  private final Optional<String> projectDescription;

  private final OffsetDateTime createdAt;

  private final int sourceLanguage;

  private final List<Integer> targetLanguages;

  private final Optional<Double> duration;

  private final Optional<Integer> folderId;

  private final String studioUrl;

  private final Map<String, Object> additionalProperties;

  private ProjectDetails(String projectName, Optional<String> projectDescription,
      OffsetDateTime createdAt, int sourceLanguage, List<Integer> targetLanguages,
      Optional<Double> duration, Optional<Integer> folderId, String studioUrl,
      Map<String, Object> additionalProperties) {
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.createdAt = createdAt;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguages = targetLanguages;
    this.duration = duration;
    this.folderId = folderId;
    this.studioUrl = studioUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("project_name")
  public String getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("created_at")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_languages")
  public List<Integer> getTargetLanguages() {
    return targetLanguages;
  }

  @JsonProperty("duration")
  public Optional<Double> getDuration() {
    return duration;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @JsonProperty("studio_url")
  public String getStudioUrl() {
    return studioUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ProjectDetails && equalTo((ProjectDetails) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ProjectDetails other) {
    return projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && createdAt.equals(other.createdAt) && sourceLanguage == other.sourceLanguage && targetLanguages.equals(other.targetLanguages) && duration.equals(other.duration) && folderId.equals(other.folderId) && studioUrl.equals(other.studioUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.projectName, this.projectDescription, this.createdAt, this.sourceLanguage, this.targetLanguages, this.duration, this.folderId, this.studioUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ProjectNameStage builder() {
    return new Builder();
  }

  public interface ProjectNameStage {
    CreatedAtStage projectName(@NotNull String projectName);

    Builder from(ProjectDetails other);
  }

  public interface CreatedAtStage {
    SourceLanguageStage createdAt(@NotNull OffsetDateTime createdAt);
  }

  public interface SourceLanguageStage {
    StudioUrlStage sourceLanguage(int sourceLanguage);
  }

  public interface StudioUrlStage {
    _FinalStage studioUrl(@NotNull String studioUrl);
  }

  public interface _FinalStage {
    ProjectDetails build();

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage targetLanguages(List<Integer> targetLanguages);

    _FinalStage addTargetLanguages(Integer targetLanguages);

    _FinalStage addAllTargetLanguages(List<Integer> targetLanguages);

    _FinalStage duration(Optional<Double> duration);

    _FinalStage duration(Double duration);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ProjectNameStage, CreatedAtStage, SourceLanguageStage, StudioUrlStage, _FinalStage {
    private String projectName;

    private OffsetDateTime createdAt;

    private int sourceLanguage;

    private String studioUrl;

    private Optional<Integer> folderId = Optional.empty();

    private Optional<Double> duration = Optional.empty();

    private List<Integer> targetLanguages = new ArrayList<>();

    private Optional<String> projectDescription = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ProjectDetails other) {
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      createdAt(other.getCreatedAt());
      sourceLanguage(other.getSourceLanguage());
      targetLanguages(other.getTargetLanguages());
      duration(other.getDuration());
      folderId(other.getFolderId());
      studioUrl(other.getStudioUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("project_name")
    public CreatedAtStage projectName(@NotNull String projectName) {
      this.projectName = Objects.requireNonNull(projectName, "projectName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("created_at")
    public SourceLanguageStage createdAt(@NotNull OffsetDateTime createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public StudioUrlStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("studio_url")
    public _FinalStage studioUrl(@NotNull String studioUrl) {
      this.studioUrl = Objects.requireNonNull(studioUrl, "studioUrl must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage duration(Double duration) {
      this.duration = Optional.ofNullable(duration);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "duration",
        nulls = Nulls.SKIP
    )
    public _FinalStage duration(Optional<Double> duration) {
      this.duration = duration;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllTargetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages.addAll(targetLanguages);
      return this;
    }

    @java.lang.Override
    public _FinalStage addTargetLanguages(Integer targetLanguages) {
      this.targetLanguages.add(targetLanguages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages.clear();
      this.targetLanguages.addAll(targetLanguages);
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public ProjectDetails build() {
      return new ProjectDetails(projectName, projectDescription, createdAt, sourceLanguage, targetLanguages, duration, folderId, studioUrl, additionalProperties);
    }
  }
}
