/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RunIDsRequestPayload.Builder.class
)
public final class RunIDsRequestPayload {
  private final List<Integer> runIds;

  private final Map<String, Object> additionalProperties;

  private RunIDsRequestPayload(List<Integer> runIds, Map<String, Object> additionalProperties) {
    this.runIds = runIds;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_ids")
  public List<Integer> getRunIds() {
    return runIds;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RunIDsRequestPayload && equalTo((RunIDsRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RunIDsRequestPayload other) {
    return runIds.equals(other.runIds);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runIds);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<Integer> runIds = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(RunIDsRequestPayload other) {
      runIds(other.getRunIds());
      return this;
    }

    @JsonSetter(
        value = "run_ids",
        nulls = Nulls.SKIP
    )
    public Builder runIds(List<Integer> runIds) {
      this.runIds.clear();
      this.runIds.addAll(runIds);
      return this;
    }

    public Builder addRunIds(Integer runIds) {
      this.runIds.add(runIds);
      return this;
    }

    public Builder addAllRunIds(List<Integer> runIds) {
      this.runIds.addAll(runIds);
      return this;
    }

    public RunIDsRequestPayload build() {
      return new RunIDsRequestPayload(runIds, additionalProperties);
    }
  }
}
