/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum SegmentingOption {
  NONE("none"),

  LOUDNESS("loudness"),

  BEST_MODEL("best_model"),

  FAST_MODEL("fast_model");

  private final String value;

  SegmentingOption(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
