/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StoryDetails.Builder.class
)
public final class StoryDetails {
  private final String storyTitle;

  private final Optional<String> storyDescription;

  private final OffsetDateTime createdAt;

  private final int sourceLanguage;

  private final Optional<List<Integer>> targetLanguages;

  private final Optional<Integer> folderId;

  private final String studioUrl;

  private final Map<String, Object> additionalProperties;

  private StoryDetails(String storyTitle, Optional<String> storyDescription,
      OffsetDateTime createdAt, int sourceLanguage, Optional<List<Integer>> targetLanguages,
      Optional<Integer> folderId, String studioUrl, Map<String, Object> additionalProperties) {
    this.storyTitle = storyTitle;
    this.storyDescription = storyDescription;
    this.createdAt = createdAt;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguages = targetLanguages;
    this.folderId = folderId;
    this.studioUrl = studioUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("story_title")
  public String getStoryTitle() {
    return storyTitle;
  }

  @JsonProperty("story_description")
  public Optional<String> getStoryDescription() {
    return storyDescription;
  }

  @JsonProperty("created_at")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_languages")
  public Optional<List<Integer>> getTargetLanguages() {
    return targetLanguages;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @JsonProperty("studio_url")
  public String getStudioUrl() {
    return studioUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StoryDetails && equalTo((StoryDetails) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StoryDetails other) {
    return storyTitle.equals(other.storyTitle) && storyDescription.equals(other.storyDescription) && createdAt.equals(other.createdAt) && sourceLanguage == other.sourceLanguage && targetLanguages.equals(other.targetLanguages) && folderId.equals(other.folderId) && studioUrl.equals(other.studioUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.storyTitle, this.storyDescription, this.createdAt, this.sourceLanguage, this.targetLanguages, this.folderId, this.studioUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StoryTitleStage builder() {
    return new Builder();
  }

  public interface StoryTitleStage {
    CreatedAtStage storyTitle(@NotNull String storyTitle);

    Builder from(StoryDetails other);
  }

  public interface CreatedAtStage {
    SourceLanguageStage createdAt(@NotNull OffsetDateTime createdAt);
  }

  public interface SourceLanguageStage {
    StudioUrlStage sourceLanguage(int sourceLanguage);
  }

  public interface StudioUrlStage {
    _FinalStage studioUrl(@NotNull String studioUrl);
  }

  public interface _FinalStage {
    StoryDetails build();

    _FinalStage storyDescription(Optional<String> storyDescription);

    _FinalStage storyDescription(String storyDescription);

    _FinalStage targetLanguages(Optional<List<Integer>> targetLanguages);

    _FinalStage targetLanguages(List<Integer> targetLanguages);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StoryTitleStage, CreatedAtStage, SourceLanguageStage, StudioUrlStage, _FinalStage {
    private String storyTitle;

    private OffsetDateTime createdAt;

    private int sourceLanguage;

    private String studioUrl;

    private Optional<Integer> folderId = Optional.empty();

    private Optional<List<Integer>> targetLanguages = Optional.empty();

    private Optional<String> storyDescription = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(StoryDetails other) {
      storyTitle(other.getStoryTitle());
      storyDescription(other.getStoryDescription());
      createdAt(other.getCreatedAt());
      sourceLanguage(other.getSourceLanguage());
      targetLanguages(other.getTargetLanguages());
      folderId(other.getFolderId());
      studioUrl(other.getStudioUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("story_title")
    public CreatedAtStage storyTitle(@NotNull String storyTitle) {
      this.storyTitle = Objects.requireNonNull(storyTitle, "storyTitle must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("created_at")
    public SourceLanguageStage createdAt(@NotNull OffsetDateTime createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public StudioUrlStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("studio_url")
    public _FinalStage studioUrl(@NotNull String studioUrl) {
      this.studioUrl = Objects.requireNonNull(studioUrl, "studioUrl must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage targetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages = Optional.ofNullable(targetLanguages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "target_languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetLanguages(Optional<List<Integer>> targetLanguages) {
      this.targetLanguages = targetLanguages;
      return this;
    }

    @java.lang.Override
    public _FinalStage storyDescription(String storyDescription) {
      this.storyDescription = Optional.ofNullable(storyDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "story_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage storyDescription(Optional<String> storyDescription) {
      this.storyDescription = storyDescription;
      return this;
    }

    @java.lang.Override
    public StoryDetails build() {
      return new StoryDetails(storyTitle, storyDescription, createdAt, sourceLanguage, targetLanguages, folderId, studioUrl, additionalProperties);
    }
  }
}
