/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StreamTtsVoiceSettings.Builder.class
)
public final class StreamTtsVoiceSettings {
  private final Optional<Boolean> enhanceReferenceAudioQuality;

  private final Optional<Boolean> maintainSourceAccent;

  private final Map<String, Object> additionalProperties;

  private StreamTtsVoiceSettings(Optional<Boolean> enhanceReferenceAudioQuality,
      Optional<Boolean> maintainSourceAccent, Map<String, Object> additionalProperties) {
    this.enhanceReferenceAudioQuality = enhanceReferenceAudioQuality;
    this.maintainSourceAccent = maintainSourceAccent;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("enhance_reference_audio_quality")
  public Optional<Boolean> getEnhanceReferenceAudioQuality() {
    return enhanceReferenceAudioQuality;
  }

  @JsonProperty("maintain_source_accent")
  public Optional<Boolean> getMaintainSourceAccent() {
    return maintainSourceAccent;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StreamTtsVoiceSettings && equalTo((StreamTtsVoiceSettings) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StreamTtsVoiceSettings other) {
    return enhanceReferenceAudioQuality.equals(other.enhanceReferenceAudioQuality) && maintainSourceAccent.equals(other.maintainSourceAccent);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.enhanceReferenceAudioQuality, this.maintainSourceAccent);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> enhanceReferenceAudioQuality = Optional.empty();

    private Optional<Boolean> maintainSourceAccent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StreamTtsVoiceSettings other) {
      enhanceReferenceAudioQuality(other.getEnhanceReferenceAudioQuality());
      maintainSourceAccent(other.getMaintainSourceAccent());
      return this;
    }

    @JsonSetter(
        value = "enhance_reference_audio_quality",
        nulls = Nulls.SKIP
    )
    public Builder enhanceReferenceAudioQuality(Optional<Boolean> enhanceReferenceAudioQuality) {
      this.enhanceReferenceAudioQuality = enhanceReferenceAudioQuality;
      return this;
    }

    public Builder enhanceReferenceAudioQuality(Boolean enhanceReferenceAudioQuality) {
      this.enhanceReferenceAudioQuality = Optional.ofNullable(enhanceReferenceAudioQuality);
      return this;
    }

    @JsonSetter(
        value = "maintain_source_accent",
        nulls = Nulls.SKIP
    )
    public Builder maintainSourceAccent(Optional<Boolean> maintainSourceAccent) {
      this.maintainSourceAccent = maintainSourceAccent;
      return this;
    }

    public Builder maintainSourceAccent(Boolean maintainSourceAccent) {
      this.maintainSourceAccent = Optional.ofNullable(maintainSourceAccent);
      return this;
    }

    public StreamTtsVoiceSettings build() {
      return new StreamTtsVoiceSettings(enhanceReferenceAudioQuality, maintainSourceAccent, additionalProperties);
    }
  }
}
