/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StreamUrlForLanguages.Builder.class
)
public final class StreamUrlForLanguages {
  private final List<Integer> languages;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private StreamUrlForLanguages(List<Integer> languages, String url,
      Map<String, Object> additionalProperties) {
    this.languages = languages;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("languages")
  public List<Integer> getLanguages() {
    return languages;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StreamUrlForLanguages && equalTo((StreamUrlForLanguages) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StreamUrlForLanguages other) {
    return languages.equals(other.languages) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.languages, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);

    Builder from(StreamUrlForLanguages other);
  }

  public interface _FinalStage {
    StreamUrlForLanguages build();

    _FinalStage languages(List<Integer> languages);

    _FinalStage addLanguages(Integer languages);

    _FinalStage addAllLanguages(List<Integer> languages);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private List<Integer> languages = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(StreamUrlForLanguages other) {
      languages(other.getLanguages());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLanguages(List<Integer> languages) {
      this.languages.addAll(languages);
      return this;
    }

    @java.lang.Override
    public _FinalStage addLanguages(Integer languages) {
      this.languages.add(languages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage languages(List<Integer> languages) {
      this.languages.clear();
      this.languages.addAll(languages);
      return this;
    }

    @java.lang.Override
    public StreamUrlForLanguages build() {
      return new StreamUrlForLanguages(languages, url, additionalProperties);
    }
  }
}
