/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StreamTtsInferenceOptions.Builder.class
)
public final class StreamTtsInferenceOptions {
  private final Optional<Double> stability;

  private final Optional<Double> temperature;

  private final Optional<Integer> inferenceSteps;

  private final Optional<Double> speakerSimilarity;

  private final Optional<Double> localizeSpeakerWeight;

  private final Optional<Boolean> acousticQualityBoost;

  private final Map<String, Object> additionalProperties;

  private StreamTtsInferenceOptions(Optional<Double> stability, Optional<Double> temperature,
      Optional<Integer> inferenceSteps, Optional<Double> speakerSimilarity,
      Optional<Double> localizeSpeakerWeight, Optional<Boolean> acousticQualityBoost,
      Map<String, Object> additionalProperties) {
    this.stability = stability;
    this.temperature = temperature;
    this.inferenceSteps = inferenceSteps;
    this.speakerSimilarity = speakerSimilarity;
    this.localizeSpeakerWeight = localizeSpeakerWeight;
    this.acousticQualityBoost = acousticQualityBoost;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("stability")
  public Optional<Double> getStability() {
    return stability;
  }

  @JsonProperty("temperature")
  public Optional<Double> getTemperature() {
    return temperature;
  }

  @JsonProperty("inference_steps")
  public Optional<Integer> getInferenceSteps() {
    return inferenceSteps;
  }

  @JsonProperty("speaker_similarity")
  public Optional<Double> getSpeakerSimilarity() {
    return speakerSimilarity;
  }

  @JsonProperty("localize_speaker_weight")
  public Optional<Double> getLocalizeSpeakerWeight() {
    return localizeSpeakerWeight;
  }

  @JsonProperty("acoustic_quality_boost")
  public Optional<Boolean> getAcousticQualityBoost() {
    return acousticQualityBoost;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StreamTtsInferenceOptions && equalTo((StreamTtsInferenceOptions) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StreamTtsInferenceOptions other) {
    return stability.equals(other.stability) && temperature.equals(other.temperature) && inferenceSteps.equals(other.inferenceSteps) && speakerSimilarity.equals(other.speakerSimilarity) && localizeSpeakerWeight.equals(other.localizeSpeakerWeight) && acousticQualityBoost.equals(other.acousticQualityBoost);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.stability, this.temperature, this.inferenceSteps, this.speakerSimilarity, this.localizeSpeakerWeight, this.acousticQualityBoost);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> stability = Optional.empty();

    private Optional<Double> temperature = Optional.empty();

    private Optional<Integer> inferenceSteps = Optional.empty();

    private Optional<Double> speakerSimilarity = Optional.empty();

    private Optional<Double> localizeSpeakerWeight = Optional.empty();

    private Optional<Boolean> acousticQualityBoost = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StreamTtsInferenceOptions other) {
      stability(other.getStability());
      temperature(other.getTemperature());
      inferenceSteps(other.getInferenceSteps());
      speakerSimilarity(other.getSpeakerSimilarity());
      localizeSpeakerWeight(other.getLocalizeSpeakerWeight());
      acousticQualityBoost(other.getAcousticQualityBoost());
      return this;
    }

    @JsonSetter(
        value = "stability",
        nulls = Nulls.SKIP
    )
    public Builder stability(Optional<Double> stability) {
      this.stability = stability;
      return this;
    }

    public Builder stability(Double stability) {
      this.stability = Optional.ofNullable(stability);
      return this;
    }

    @JsonSetter(
        value = "temperature",
        nulls = Nulls.SKIP
    )
    public Builder temperature(Optional<Double> temperature) {
      this.temperature = temperature;
      return this;
    }

    public Builder temperature(Double temperature) {
      this.temperature = Optional.ofNullable(temperature);
      return this;
    }

    @JsonSetter(
        value = "inference_steps",
        nulls = Nulls.SKIP
    )
    public Builder inferenceSteps(Optional<Integer> inferenceSteps) {
      this.inferenceSteps = inferenceSteps;
      return this;
    }

    public Builder inferenceSteps(Integer inferenceSteps) {
      this.inferenceSteps = Optional.ofNullable(inferenceSteps);
      return this;
    }

    @JsonSetter(
        value = "speaker_similarity",
        nulls = Nulls.SKIP
    )
    public Builder speakerSimilarity(Optional<Double> speakerSimilarity) {
      this.speakerSimilarity = speakerSimilarity;
      return this;
    }

    public Builder speakerSimilarity(Double speakerSimilarity) {
      this.speakerSimilarity = Optional.ofNullable(speakerSimilarity);
      return this;
    }

    @JsonSetter(
        value = "localize_speaker_weight",
        nulls = Nulls.SKIP
    )
    public Builder localizeSpeakerWeight(Optional<Double> localizeSpeakerWeight) {
      this.localizeSpeakerWeight = localizeSpeakerWeight;
      return this;
    }

    public Builder localizeSpeakerWeight(Double localizeSpeakerWeight) {
      this.localizeSpeakerWeight = Optional.ofNullable(localizeSpeakerWeight);
      return this;
    }

    @JsonSetter(
        value = "acoustic_quality_boost",
        nulls = Nulls.SKIP
    )
    public Builder acousticQualityBoost(Optional<Boolean> acousticQualityBoost) {
      this.acousticQualityBoost = acousticQualityBoost;
      return this;
    }

    public Builder acousticQualityBoost(Boolean acousticQualityBoost) {
      this.acousticQualityBoost = Optional.ofNullable(acousticQualityBoost);
      return this;
    }

    public StreamTtsInferenceOptions build() {
      return new StreamTtsInferenceOptions(stability, temperature, inferenceSteps, speakerSimilarity, localizeSpeakerWeight, acousticQualityBoost, additionalProperties);
    }
  }
}
