/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TaskStatus {
  SUCCESS("SUCCESS"),

  PENDING("PENDING"),

  ERROR("ERROR");

  private final String value;

  TaskStatus(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
