/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TermTranslationInput.Builder.class
)
public final class TermTranslationInput {
  private final String translation;

  private final int language;

  private final Map<String, Object> additionalProperties;

  private TermTranslationInput(String translation, int language,
      Map<String, Object> additionalProperties) {
    this.translation = translation;
    this.language = language;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("translation")
  public String getTranslation() {
    return translation;
  }

  @JsonProperty("language")
  public int getLanguage() {
    return language;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TermTranslationInput && equalTo((TermTranslationInput) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TermTranslationInput other) {
    return translation.equals(other.translation) && language == other.language;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.translation, this.language);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TranslationStage builder() {
    return new Builder();
  }

  public interface TranslationStage {
    LanguageStage translation(@NotNull String translation);

    Builder from(TermTranslationInput other);
  }

  public interface LanguageStage {
    _FinalStage language(int language);
  }

  public interface _FinalStage {
    TermTranslationInput build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TranslationStage, LanguageStage, _FinalStage {
    private String translation;

    private int language;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TermTranslationInput other) {
      translation(other.getTranslation());
      language(other.getLanguage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("translation")
    public LanguageStage translation(@NotNull String translation) {
      this.translation = Objects.requireNonNull(translation, "translation must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("language")
    public _FinalStage language(int language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    public TermTranslationInput build() {
      return new TermTranslationInput(translation, language, additionalProperties);
    }
  }
}
