/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Transcript.Builder.class
)
public final class Transcript {
  private final double start;

  private final double end;

  private final String text;

  private final String speaker;

  private final Map<String, Object> additionalProperties;

  private Transcript(double start, double end, String text, String speaker,
      Map<String, Object> additionalProperties) {
    this.start = start;
    this.end = end;
    this.text = text;
    this.speaker = speaker;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("start")
  public double getStart() {
    return start;
  }

  @JsonProperty("end")
  public double getEnd() {
    return end;
  }

  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @JsonProperty("speaker")
  public String getSpeaker() {
    return speaker;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Transcript && equalTo((Transcript) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Transcript other) {
    return start == other.start && end == other.end && text.equals(other.text) && speaker.equals(other.speaker);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.start, this.end, this.text, this.speaker);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StartStage builder() {
    return new Builder();
  }

  public interface StartStage {
    EndStage start(double start);

    Builder from(Transcript other);
  }

  public interface EndStage {
    TextStage end(double end);
  }

  public interface TextStage {
    SpeakerStage text(@NotNull String text);
  }

  public interface SpeakerStage {
    _FinalStage speaker(@NotNull String speaker);
  }

  public interface _FinalStage {
    Transcript build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StartStage, EndStage, TextStage, SpeakerStage, _FinalStage {
    private double start;

    private double end;

    private String text;

    private String speaker;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Transcript other) {
      start(other.getStart());
      end(other.getEnd());
      text(other.getText());
      speaker(other.getSpeaker());
      return this;
    }

    @java.lang.Override
    @JsonSetter("start")
    public EndStage start(double start) {
      this.start = start;
      return this;
    }

    @java.lang.Override
    @JsonSetter("end")
    public TextStage end(double end) {
      this.end = end;
      return this;
    }

    @java.lang.Override
    @JsonSetter("text")
    public SpeakerStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("speaker")
    public _FinalStage speaker(@NotNull String speaker) {
      this.speaker = Objects.requireNonNull(speaker, "speaker must not be null");
      return this;
    }

    @java.lang.Override
    public Transcript build() {
      return new Transcript(start, end, text, speaker, additionalProperties);
    }
  }
}
