/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TranscriptFileFormat {
  SRT("srt"),

  VTT("vtt"),

  TXT("txt");

  private final String value;

  TranscriptFileFormat(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
