/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TranscriptDataType {
  RAW_DATA("raw_data"),

  FILE("file");

  private final String value;

  TranscriptDataType(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
