/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TranscriptionResult.Builder.class
)
public final class TranscriptionResult {
  private final List<Transcript> transcript;

  private final Map<String, Object> additionalProperties;

  private TranscriptionResult(List<Transcript> transcript,
      Map<String, Object> additionalProperties) {
    this.transcript = transcript;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("transcript")
  public List<Transcript> getTranscript() {
    return transcript;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TranscriptionResult && equalTo((TranscriptionResult) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TranscriptionResult other) {
    return transcript.equals(other.transcript);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.transcript);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<Transcript> transcript = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TranscriptionResult other) {
      transcript(other.getTranscript());
      return this;
    }

    @JsonSetter(
        value = "transcript",
        nulls = Nulls.SKIP
    )
    public Builder transcript(List<Transcript> transcript) {
      this.transcript.clear();
      this.transcript.addAll(transcript);
      return this;
    }

    public Builder addTranscript(Transcript transcript) {
      this.transcript.add(transcript);
      return this;
    }

    public Builder addAllTranscript(List<Transcript> transcript) {
      this.transcript.addAll(transcript);
      return this;
    }

    public TranscriptionResult build() {
      return new TranscriptionResult(transcript, additionalProperties);
    }
  }
}
