/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum VideoOutputTypeWithoutAvi {
  MKV("mkv"),

  MP4("mp4"),

  MOV("mov"),

  MXF("mxf");

  private final String value;

  VideoOutputTypeWithoutAvi(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
