/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = VideoStream.Builder.class
)
public final class VideoStream {
  private final int index;

  private final String codecName;

  private final String codecLongName;

  private final Optional<String> codecTagString;

  private final Optional<String> codecTag;

  private final Optional<String> profile;

  private final Optional<Integer> width;

  private final Optional<Integer> height;

  private final Optional<Boolean> isAvc;

  private final Optional<String> id;

  private final Map<String, Object> additionalProperties;

  private VideoStream(int index, String codecName, String codecLongName,
      Optional<String> codecTagString, Optional<String> codecTag, Optional<String> profile,
      Optional<Integer> width, Optional<Integer> height, Optional<Boolean> isAvc,
      Optional<String> id, Map<String, Object> additionalProperties) {
    this.index = index;
    this.codecName = codecName;
    this.codecLongName = codecLongName;
    this.codecTagString = codecTagString;
    this.codecTag = codecTag;
    this.profile = profile;
    this.width = width;
    this.height = height;
    this.isAvc = isAvc;
    this.id = id;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("index")
  public int getIndex() {
    return index;
  }

  @JsonProperty("codec_name")
  public String getCodecName() {
    return codecName;
  }

  @JsonProperty("codec_long_name")
  public String getCodecLongName() {
    return codecLongName;
  }

  @JsonProperty("codec_tag_string")
  public Optional<String> getCodecTagString() {
    return codecTagString;
  }

  @JsonProperty("codec_tag")
  public Optional<String> getCodecTag() {
    return codecTag;
  }

  @JsonProperty("profile")
  public Optional<String> getProfile() {
    return profile;
  }

  @JsonProperty("width")
  public Optional<Integer> getWidth() {
    return width;
  }

  @JsonProperty("height")
  public Optional<Integer> getHeight() {
    return height;
  }

  @JsonProperty("is_avc")
  public Optional<Boolean> getIsAvc() {
    return isAvc;
  }

  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof VideoStream && equalTo((VideoStream) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(VideoStream other) {
    return index == other.index && codecName.equals(other.codecName) && codecLongName.equals(other.codecLongName) && codecTagString.equals(other.codecTagString) && codecTag.equals(other.codecTag) && profile.equals(other.profile) && width.equals(other.width) && height.equals(other.height) && isAvc.equals(other.isAvc) && id.equals(other.id);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.index, this.codecName, this.codecLongName, this.codecTagString, this.codecTag, this.profile, this.width, this.height, this.isAvc, this.id);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IndexStage builder() {
    return new Builder();
  }

  public interface IndexStage {
    CodecNameStage index(int index);

    Builder from(VideoStream other);
  }

  public interface CodecNameStage {
    CodecLongNameStage codecName(@NotNull String codecName);
  }

  public interface CodecLongNameStage {
    _FinalStage codecLongName(@NotNull String codecLongName);
  }

  public interface _FinalStage {
    VideoStream build();

    _FinalStage codecTagString(Optional<String> codecTagString);

    _FinalStage codecTagString(String codecTagString);

    _FinalStage codecTag(Optional<String> codecTag);

    _FinalStage codecTag(String codecTag);

    _FinalStage profile(Optional<String> profile);

    _FinalStage profile(String profile);

    _FinalStage width(Optional<Integer> width);

    _FinalStage width(Integer width);

    _FinalStage height(Optional<Integer> height);

    _FinalStage height(Integer height);

    _FinalStage isAvc(Optional<Boolean> isAvc);

    _FinalStage isAvc(Boolean isAvc);

    _FinalStage id(Optional<String> id);

    _FinalStage id(String id);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IndexStage, CodecNameStage, CodecLongNameStage, _FinalStage {
    private int index;

    private String codecName;

    private String codecLongName;

    private Optional<String> id = Optional.empty();

    private Optional<Boolean> isAvc = Optional.empty();

    private Optional<Integer> height = Optional.empty();

    private Optional<Integer> width = Optional.empty();

    private Optional<String> profile = Optional.empty();

    private Optional<String> codecTag = Optional.empty();

    private Optional<String> codecTagString = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(VideoStream other) {
      index(other.getIndex());
      codecName(other.getCodecName());
      codecLongName(other.getCodecLongName());
      codecTagString(other.getCodecTagString());
      codecTag(other.getCodecTag());
      profile(other.getProfile());
      width(other.getWidth());
      height(other.getHeight());
      isAvc(other.getIsAvc());
      id(other.getId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("index")
    public CodecNameStage index(int index) {
      this.index = index;
      return this;
    }

    @java.lang.Override
    @JsonSetter("codec_name")
    public CodecLongNameStage codecName(@NotNull String codecName) {
      this.codecName = Objects.requireNonNull(codecName, "codecName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("codec_long_name")
    public _FinalStage codecLongName(@NotNull String codecLongName) {
      this.codecLongName = Objects.requireNonNull(codecLongName, "codecLongName must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public _FinalStage id(Optional<String> id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    public _FinalStage isAvc(Boolean isAvc) {
      this.isAvc = Optional.ofNullable(isAvc);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "is_avc",
        nulls = Nulls.SKIP
    )
    public _FinalStage isAvc(Optional<Boolean> isAvc) {
      this.isAvc = isAvc;
      return this;
    }

    @java.lang.Override
    public _FinalStage height(Integer height) {
      this.height = Optional.ofNullable(height);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "height",
        nulls = Nulls.SKIP
    )
    public _FinalStage height(Optional<Integer> height) {
      this.height = height;
      return this;
    }

    @java.lang.Override
    public _FinalStage width(Integer width) {
      this.width = Optional.ofNullable(width);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "width",
        nulls = Nulls.SKIP
    )
    public _FinalStage width(Optional<Integer> width) {
      this.width = width;
      return this;
    }

    @java.lang.Override
    public _FinalStage profile(String profile) {
      this.profile = Optional.ofNullable(profile);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "profile",
        nulls = Nulls.SKIP
    )
    public _FinalStage profile(Optional<String> profile) {
      this.profile = profile;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTag(String codecTag) {
      this.codecTag = Optional.ofNullable(codecTag);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_tag",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecTag(Optional<String> codecTag) {
      this.codecTag = codecTag;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTagString(String codecTagString) {
      this.codecTagString = Optional.ofNullable(codecTagString);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_tag_string",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecTagString(Optional<String> codecTagString) {
      this.codecTagString = codecTagString;
      return this;
    }

    @java.lang.Override
    public VideoStream build() {
      return new VideoStream(index, codecName, codecLongName, codecTagString, codecTag, profile, width, height, isAvc, id, additionalProperties);
    }
  }
}
