/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.streaming.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateStreamDataRequestPayload.Builder.class
)
public final class UpdateStreamDataRequestPayload {
  private final Optional<Integer> runId;

  private final Optional<OffsetDateTime> startTime;

  private final Optional<OffsetDateTime> endTime;

  private final Optional<Map<String, Object>> payload;

  private final Optional<List<Integer>> targetLanguages;

  private final Optional<String> timezone;

  private final Map<String, Object> additionalProperties;

  private UpdateStreamDataRequestPayload(Optional<Integer> runId,
      Optional<OffsetDateTime> startTime, Optional<OffsetDateTime> endTime,
      Optional<Map<String, Object>> payload, Optional<List<Integer>> targetLanguages,
      Optional<String> timezone, Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.startTime = startTime;
    this.endTime = endTime;
    this.payload = payload;
    this.targetLanguages = targetLanguages;
    this.timezone = timezone;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("start_time")
  public Optional<OffsetDateTime> getStartTime() {
    return startTime;
  }

  @JsonProperty("end_time")
  public Optional<OffsetDateTime> getEndTime() {
    return endTime;
  }

  @JsonProperty("payload")
  public Optional<Map<String, Object>> getPayload() {
    return payload;
  }

  @JsonProperty("target_languages")
  public Optional<List<Integer>> getTargetLanguages() {
    return targetLanguages;
  }

  @JsonProperty("timezone")
  public Optional<String> getTimezone() {
    return timezone;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateStreamDataRequestPayload && equalTo((UpdateStreamDataRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateStreamDataRequestPayload other) {
    return runId.equals(other.runId) && startTime.equals(other.startTime) && endTime.equals(other.endTime) && payload.equals(other.payload) && targetLanguages.equals(other.targetLanguages) && timezone.equals(other.timezone);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.startTime, this.endTime, this.payload, this.targetLanguages, this.timezone);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> runId = Optional.empty();

    private Optional<OffsetDateTime> startTime = Optional.empty();

    private Optional<OffsetDateTime> endTime = Optional.empty();

    private Optional<Map<String, Object>> payload = Optional.empty();

    private Optional<List<Integer>> targetLanguages = Optional.empty();

    private Optional<String> timezone = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdateStreamDataRequestPayload other) {
      runId(other.getRunId());
      startTime(other.getStartTime());
      endTime(other.getEndTime());
      payload(other.getPayload());
      targetLanguages(other.getTargetLanguages());
      timezone(other.getTimezone());
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @JsonSetter(
        value = "start_time",
        nulls = Nulls.SKIP
    )
    public Builder startTime(Optional<OffsetDateTime> startTime) {
      this.startTime = startTime;
      return this;
    }

    public Builder startTime(OffsetDateTime startTime) {
      this.startTime = Optional.ofNullable(startTime);
      return this;
    }

    @JsonSetter(
        value = "end_time",
        nulls = Nulls.SKIP
    )
    public Builder endTime(Optional<OffsetDateTime> endTime) {
      this.endTime = endTime;
      return this;
    }

    public Builder endTime(OffsetDateTime endTime) {
      this.endTime = Optional.ofNullable(endTime);
      return this;
    }

    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public Builder payload(Optional<Map<String, Object>> payload) {
      this.payload = payload;
      return this;
    }

    public Builder payload(Map<String, Object> payload) {
      this.payload = Optional.ofNullable(payload);
      return this;
    }

    @JsonSetter(
        value = "target_languages",
        nulls = Nulls.SKIP
    )
    public Builder targetLanguages(Optional<List<Integer>> targetLanguages) {
      this.targetLanguages = targetLanguages;
      return this;
    }

    public Builder targetLanguages(List<Integer> targetLanguages) {
      this.targetLanguages = Optional.ofNullable(targetLanguages);
      return this;
    }

    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public Builder timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    public Builder timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    public UpdateStreamDataRequestPayload build() {
      return new UpdateStreamDataRequestPayload(runId, startTime, endTime, payload, targetLanguages, timezone, additionalProperties);
    }
  }
}
