/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translation.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTranslationStreamRequestPayload.Builder.class
)
public final class CreateTranslationStreamRequestPayload {
  private final Optional<String> traceparent;

  private final int sourceLanguage;

  private final int targetLanguage;

  private final String text;

  private final Optional<Integer> formality;

  private final Optional<Integer> gender;

  private final Optional<Integer> teamId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final Map<String, Object> additionalProperties;

  private CreateTranslationStreamRequestPayload(Optional<String> traceparent, int sourceLanguage,
      int targetLanguage, String text, Optional<Integer> formality, Optional<Integer> gender,
      Optional<Integer> teamId, Optional<String> projectName, Optional<String> projectDescription,
      Optional<Integer> folderId, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.sourceLanguage = sourceLanguage;
    this.targetLanguage = targetLanguage;
    this.text = text;
    this.formality = formality;
    this.gender = gender;
    this.teamId = teamId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("traceparent")
  public Optional<String> getTraceparent() {
    return traceparent;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonProperty("target_language")
  public int getTargetLanguage() {
    return targetLanguage;
  }

  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @JsonProperty("formality")
  public Optional<Integer> getFormality() {
    return formality;
  }

  @JsonProperty("gender")
  public Optional<Integer> getGender() {
    return gender;
  }

  @JsonProperty("team_id")
  public Optional<Integer> getTeamId() {
    return teamId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTranslationStreamRequestPayload && equalTo((CreateTranslationStreamRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTranslationStreamRequestPayload other) {
    return traceparent.equals(other.traceparent) && sourceLanguage == other.sourceLanguage && targetLanguage == other.targetLanguage && text.equals(other.text) && formality.equals(other.formality) && gender.equals(other.gender) && teamId.equals(other.teamId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.sourceLanguage, this.targetLanguage, this.text, this.formality, this.gender, this.teamId, this.projectName, this.projectDescription, this.folderId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SourceLanguageStage builder() {
    return new Builder();
  }

  public interface SourceLanguageStage {
    TargetLanguageStage sourceLanguage(int sourceLanguage);

    Builder from(CreateTranslationStreamRequestPayload other);
  }

  public interface TargetLanguageStage {
    TextStage targetLanguage(int targetLanguage);
  }

  public interface TextStage {
    _FinalStage text(@NotNull String text);
  }

  public interface _FinalStage {
    CreateTranslationStreamRequestPayload build();

    _FinalStage traceparent(Optional<String> traceparent);

    _FinalStage traceparent(String traceparent);

    _FinalStage formality(Optional<Integer> formality);

    _FinalStage formality(Integer formality);

    _FinalStage gender(Optional<Integer> gender);

    _FinalStage gender(Integer gender);

    _FinalStage teamId(Optional<Integer> teamId);

    _FinalStage teamId(Integer teamId);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SourceLanguageStage, TargetLanguageStage, TextStage, _FinalStage {
    private int sourceLanguage;

    private int targetLanguage;

    private String text;

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<Integer> teamId = Optional.empty();

    private Optional<Integer> gender = Optional.empty();

    private Optional<Integer> formality = Optional.empty();

    private Optional<String> traceparent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTranslationStreamRequestPayload other) {
      traceparent(other.getTraceparent());
      sourceLanguage(other.getSourceLanguage());
      targetLanguage(other.getTargetLanguage());
      text(other.getText());
      formality(other.getFormality());
      gender(other.getGender());
      teamId(other.getTeamId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public TargetLanguageStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("target_language")
    public TextStage targetLanguage(int targetLanguage) {
      this.targetLanguage = targetLanguage;
      return this;
    }

    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage teamId(Integer teamId) {
      this.teamId = Optional.ofNullable(teamId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "team_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage teamId(Optional<Integer> teamId) {
      this.teamId = teamId;
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(Integer gender) {
      this.gender = Optional.ofNullable(gender);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gender",
        nulls = Nulls.SKIP
    )
    public _FinalStage gender(Optional<Integer> gender) {
      this.gender = gender;
      return this;
    }

    @java.lang.Override
    public _FinalStage formality(Integer formality) {
      this.formality = Optional.ofNullable(formality);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "formality",
        nulls = Nulls.SKIP
    )
    public _FinalStage formality(Optional<Integer> formality) {
      this.formality = formality;
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public _FinalStage traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    @java.lang.Override
    public CreateTranslationStreamRequestPayload build() {
      return new CreateTranslationStreamRequestPayload(traceparent, sourceLanguage, targetLanguage, text, formality, gender, teamId, projectName, projectDescription, folderId, additionalProperties);
    }
  }
}
