/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.audioseparation.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BodyCreateAudioSeparationAudioSeparationPost.Builder.class
)
public final class BodyCreateAudioSeparationAudioSeparationPost {
  private final Optional<String> traceparent;

  private final Optional<Integer> runId;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final Map<String, Object> additionalProperties;

  private BodyCreateAudioSeparationAudioSeparationPost(Optional<String> traceparent,
      Optional<Integer> runId, Optional<String> projectName, Optional<String> projectDescription,
      Optional<Integer> folderId, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.runId = runId;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("traceparent")
  public Optional<String> getTraceparent() {
    return traceparent;
  }

  @JsonProperty("run_id")
  public Optional<Integer> getRunId() {
    return runId;
  }

  @JsonProperty("project_name")
  public Optional<String> getProjectName() {
    return projectName;
  }

  @JsonProperty("project_description")
  public Optional<String> getProjectDescription() {
    return projectDescription;
  }

  @JsonProperty("folder_id")
  public Optional<Integer> getFolderId() {
    return folderId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BodyCreateAudioSeparationAudioSeparationPost && equalTo((BodyCreateAudioSeparationAudioSeparationPost) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BodyCreateAudioSeparationAudioSeparationPost other) {
    return traceparent.equals(other.traceparent) && runId.equals(other.runId) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.runId, this.projectName, this.projectDescription, this.folderId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> traceparent = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<Integer> folderId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BodyCreateAudioSeparationAudioSeparationPost other) {
      traceparent(other.getTraceparent());
      runId(other.getRunId());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      return this;
    }

    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public Builder traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    public Builder traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public Builder projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    public Builder projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public Builder projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    public Builder projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public Builder folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    public Builder folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    public BodyCreateAudioSeparationAudioSeparationPost build() {
      return new BodyCreateAudioSeparationAudioSeparationPost(traceparent, runId, projectName, projectDescription, folderId, additionalProperties);
    }
  }
}
